### ISSUE TITLE
ImagePage: Zoom SVG image in-out

### ISSUE THREAD

**Issue by gjwgit** [gjwgit/rattle#181]
For the SVG image, would be great to be able to zoom in and out.

**Comment by yixiangyin** [comment]
<img width="1352" alt="Screenshot 2024-07-18 at 15 29 04" src="https://github.com/user-attachments/assets/0ecb454e-2bae-4be2-b821-ba27517e2940">

**Comment by gjwgit** [comment]
Looks good. Thanks.
