### ISSUE TITLE
SCRIPT: Ask if want to save the `script.R`

### ISSUE THREAD

**Issue by gjwgit** [gjwgit/rattle#186]
Currently, the EXPORT button in SCRIPT tab simply exports to `script.R` without even telling the user. 

A better user experience will be to popup a file chooser with `script.R` as the default filename and let the user override if desired.

**Comment by zheyxu** [comment]
![Image](https://github.com/user-attachments/assets/644d8b2f-1508-4e09-81c4-b5b08f88eb2e)

**Comment by zheyxu** [comment]
Made pr https://github.com/gjwgit/rattleng/pull/226
