### ISSUE TITLE
DATASET ROLES: Reduce the unused space to fit more on a single line

### ISSUE THREAD

**Issue by gjwgit** [gjwgit/rattle#194]
There is plenty of white space on a line yet the Variable column is being wrapped. How can this be better handled.

![Image](https://github.com/user-attachments/assets/10d9ac45-677e-4c10-918b-026c8c25189e)

**Comment by junhaow1** [comment]
https://github.com/gjwgit/rattleng/pull/386 PR created

**Comment by junhaow1** [comment]
Ensure the Variable text stays on one line.
<img width="1057" alt="image" src="https://github.com/user-attachments/assets/53f49cd1-6ff8-4ba4-ab50-b22797082f3e">

**Comment by junhaow1** [comment]
https://github.com/user-attachments/assets/de8f7a74-dbe1-4d85-bc0e-ed0d3cf3e7cd

**Comment by gjwgit** [comment]
Thanks for having a look Kevin.  Not quite what I had in mind. I don;t mind the variables wrapping on very narrow screens. However it is more the space that you can very readily see in your video before and after the Roles column. Can we reduce/eliminate that space?

**Comment by junhaow1** [comment]
> Thanks for having a look Kevin. Not quite what I had in mind. I don;t mind the variables wrapping on very narrow screens. However it is more the space that you can very readily see in your video before and after the Roles column. Can we reduce/eliminate that space?

I tried that few mins ago. Got it, wont be long

**Comment by junhaow1** [comment]
https://github.com/user-attachments/assets/62ffeab7-6a78-46f7-9249-55207407b96a

Please have a look :) @gjwgit

**Comment by junhaow1** [comment]
https://github.com/gjwgit/rattleng/pull/403 PR created

**Comment by junhaow1** [comment]
put the space between the ROLES column and the DATA column to the right of the DATA column instead of between them 
https://github.com/user-attachments/assets/7323ae1d-a176-4f97-a6e1-1a0bf8c4cfc5

**Comment by junhaow1** [comment]
PR merged , can be closed
