### ISSUE TITLE
DATASET: Re-engineer display.dart to clarify the logic.

### ISSUE THREAD

**Issue by gjwgit** [gjwgit/rattle#195]
## Description

The DATASET version of `display.dart` needs to be updated to match the "quality" of the other feature `display.dart` implementation. Currently the main widget is too many layers and could do with splitting them out so the logic is more readily observed within fewer lines.

This will also better pass the lint checks.

**Comment by gjwgit** [comment]
Always good to include the output of `make qtest.tmp` here (or the equivalent for Windows). I am currently running it on Linux and will include the screenshot once finished.

**Comment by Lutra-Fs** [comment]
> Always good to include the output of `make qtest.tmp` here (or the equivalent for Windows). I am currently running it on Linux and will include the screenshot once finished.

I could use the command `make qtest`. but is there a way to hide that pesky rattle window that pops up on top every time? It's been really distracting me lately. I've got 4 deadlines coming up this week, so I'm trying to stay focused. Any tips on how to make it less intrusive would be super helpful.

**Comment by gjwgit** [comment]
I ran the tests. 3 initially failed but run separately passed. All good.

![image](https://github.com/user-attachments/assets/12c4ec54-8f80-49a0-a6ae-0bdcf68440d0)

Noted re the pesky app coming on top each test. It's been annoying me too. Need to keep an eye out for how to stop that or even suppres the window being shown.

All the best with your deadlines!
