### ISSUE TITLE
TESTS: Need config.dart to choose two variables and communicate that to the script

### ISSUE THREAD

**Issue by gjwgit** [gjwgit/rattle#199]
From Visualise use the same selectedProvider.

Add a new selected2Provider for the second variable

**Comment by yixiangyin** [comment]
What are the scripts will be used?

**Comment by gjwgit** [comment]
Added assets/r/test_correlation.R as an example. More to come.

**Comment by gjwgit** [comment]
All tests in a single script. No need for choosing amongst different tests in the GUI. Just need SELECTED_VAR, and SELECTED_2_VAR and GROUP_BY.

GROUP_BY not yet supported in test.R

**Comment by yixiangyin** [comment]
I dumped the output to the display. The warning causes the wilcox.test to be extracted twice. The warning precedes the next command. This make the output of next command also included. Can we suppress this warning somehow? @gjwgit 

![Image](https://github.com/user-attachments/assets/0189635f-4df5-4b42-9847-efa6f3d9bede)
