### ISSUE TITLE
BUG: visual images remains after reset

### ISSUE THREAD

**Issue by gjwgit** [gjwgit/rattle#201]
Probably need to delete the contents of the TEMP folder.

**Comment by zheyxu** [comment]
Made pr https://github.com/gjwgit/rattleng/pull/381

**Comment by gjwgit** [comment]
How does the PR make any sense in the context of this issue? We have a general problem across the app with managing the image files and how to know they have been properly updated, etc, and only make them available as pages when they are updated properly and available. Checking the `content` from a previous command seems rather simplistic and odd. I don't think this solves the issue - can you please explain how this fixes the issue? You've demonstrated a single "fix". What about the rest?

**Comment by zheyxu** [comment]
<img width="1243" alt="Screenshot 2024-09-04 at 1 45 00 PM" src="https://github.com/user-attachments/assets/98095e7d-3539-443c-93a3-bbdf2525f553">
The solution can be deleting images in tempVir folder after dataset reset.

**Comment by gjwgit** [comment]
Can you have a look at improving the call to Image Page to make it conditional on the image file existing, across all features that currently call ImagePage. That would be a good first start. Waht do you think? 

Thanks.
