### ISSUE TITLE
IMAGE PAGE: When full screen the image should scale to take up the whole page.

### ISSUE THREAD

**Issue by gjwgit** [gjwgit/rattle#204]
Currently the image stays the same size irrespective of the window size. As a user if I want to see the plot in more detail I would think to enlarge the window, but the image remains the same size.

![Image](https://github.com/user-attachments/assets/b6b28295-ce9b-492b-be3d-a2e742faaafe)

**Comment by yixiangyin** [comment]
The pageindicator seems to constrain the space. It is interesting that tree and wordcloud get different constraints.
![Image](https://github.com/user-attachments/assets/b31818a1-d90c-4441-8860-2e45643477db)
![Image](https://github.com/user-attachments/assets/7c944125-adcb-41af-8552-a4cb125c9970)

**Comment by junhaow1** [comment]
tested with full screen mode  on mac 

![Image](https://github.com/user-attachments/assets/81d7be89-72cc-42c3-b9c2-c9358ae620c4)

**Comment by zheyxu** [comment]
Made pr https://github.com/gjwgit/rattleng/pull/384

**Comment by gjwgit** [comment]
Looks good. Thanks @zheyxu
