### ISSUE TITLE
VISUAL: Add a Group By to the CONFIG with Target (if any) as the default

### ISSUE THREAD

**Issue by gjwgit** [gjwgit/rattle#205]
The default VISUAL R script assumes the TARGET_VAR as a group by for the charts. A user will want to choose here in the VISUAL config the actual Group By, if any. This task is to add a Group By drop down listing all variables, except the variable chosen to chart. The chosen GROUP BY variable is communicated to the R script.

**Comment by yixiangyin** [comment]
Where should the group by variable be in the script?

**Comment by gjwgit** [comment]
It should replace TARGET_VAR in the script. Probably replace that string with GROUP_BY. And by default it should be the target variable, and the oher choices should be the categorical variables.
