### ISSUE TITLE
GUI: After R scripts finish popup a SnackBar to say the plot generation is completed.

### ISSUE THREAD

**Issue by gjwgit** [gjwgit/rattle#212]
Currently there is no indication when running scripts finishes. For example the generation of the Visual plots. It would be good to popup a SnackBar message when finished.

**Comment by zheyxu** [comment]
Made pr https://github.com/gjwgit/rattleng/pull/370
![Image](https://github.com/user-attachments/assets/e71e2e0d-0d18-4c2f-985d-ce5814a50c13)

**Comment by gjwgit** [comment]
Perhaps instead of a SnackBar, update the status bar with a message like "Completed explore_summary.R" replacing the "Ready to Explore" message.

**Comment by gjwgit** [comment]
Closing the PR #370 as it is not ready for merging. The proposed solution is not a good solution. Needs more work. Moving this back into In Progress

**Comment by gjwgit** [comment]
Reviewed and added updates to status rather than a SnackBar that occludes the navigation tool. For now we'll close this as being sufficient.
