### ISSUE TITLE
[Installer] How to identify the version?

### ISSUE THREAD

**Issue by Lutra-Fs** [gjwgit/rattle#213]
Hi there, I am trying to add `winget` and `scoop` installation methods for Microsoft Windows. However, I can only find the latest zip available at `https://access.togaware.com/rattleng-dev-windows.zip` with no further version info, where it is challenging to identify the app needs update or not. I can see there are multiple commits heading Bump version x.x.x· e.g.[Bump version 6.2.9](https://github.com/gjwgit/rattleng/commit/d259fed9704db128d491f8992951188cde8cf1a4) I wonder if these commits can be used as identifiers. I would better suggest using a GitHub release, a git tag or a plain text file (or API) to get the latest release version info.
Regards.

**Comment by Lutra-Fs** [comment]
Add a nightly scoop script in my personal bucket, let me know if you met any issue using this version
```
scoop bucket add Lutra-Fs_scoop-bucket https://github.com/Lutra-Fs/scoop-bucket
scoop install Lutra-Fs_scoop-bucket/rattleng
// preferably install r through scoop
scoop install r
```
After successful installation, you would be able to seen the rattleng entry under `scoop apps` in your start menu. As this is a nightly version and we don't want to break anything, you could update the nightly version app manually via `scoop update rattleng`

**Comment by gjwgit** [comment]
For each release there is also a versioned zip file, like https://access.togaware.com/rattleng-6.2.40-windows.zip. Perhaps you can see the `Bump version 6.2.10` message and then expect to find a 6.2.10 zip version on the togware repository?

**Comment by Lutra-Fs** [comment]
> For each release there is also a versioned zip file, like [access.togaware.com/rattleng-6.2.40-windows.zip](https://access.togaware.com/rattleng-6.2.40-windows.zip). Perhaps you can see the `Bump version 6.2.10` message and then expect to find a 6.2.10 zip version on the togware repository?

Updated, the auto update should work now. note that the package name has changed so `rattleng` will no longer work. Install using
```
scoop bucket add Lutra-Fs_scoop-bucket https://github.com/Lutra-Fs/scoop-bucket
scoop install Lutra-Fs_scoop-bucket/rattle
// or nightly version, unsure if it is needed or not
scoop install Lutra-Fs_scoop-bucket/rattle-nightly
// preferably install r through scoop
scoop install r
```
