### ISSUE TITLE
Install R, Rattle and run mac app

### ISSUE THREAD

**Issue by zheyxu** [gjwgit/rattle#215]
Install R, Rattle and run desktop app on Mac.

**Comment by zheyxu** [comment]
For the first step on Mac, https://github.com/gjwgit/rattleng/blob/dev/installers/README.md#prerequisite
Using the pacman Package to install the pre-requisite packages. Otherwise, the install progress does not work. 
`install.packages('pacman')`

`pacman::p_load(rattle, magrittr, janitor, tidyverse, mice, VIM, naniar, reshape, corrplot, Hmisc, fBasics, descr, randomForest, verification, rpart, readr, tm, wordcloud, magick, ggthemes)`

**Comment by gjwgit** [comment]
Thanks for the suggestion. I have moved to using pacman in main.R. Let's see if that works seemlessly in the flutter xterm R console.

**Comment by gjwgit** [comment]
See also #125

**Comment by zheyxu** [comment]
Update mac release build permission && give full permission to the app and still cannot load dataset.
