### ISSUE TITLE
BUG:

### ISSUE THREAD

**Issue by yixiangyin** [gjwgit/rattle#216]
![Image](https://github.com/user-attachments/assets/1e4f5f2e-4121-4875-9c2b-65dc446aa061)

**Comment by gjwgit** [comment]
What was the scenario that led to this error? Looks like the providers were not yet set?

**Comment by yixiangyin** [comment]
> What was the scenario that led to this error? Looks like the providers were not yet set?

All good now. It's not a problem anymore. It was due to the installation of library I think.
