### ISSUE TITLE
CLEANUP: Implement this TRANSFORM feature

### ISSUE THREAD

**Issue by gjwgit** [gjwgit/rattle#220]
## Cleanup

- [x] delete ignored: delete the variables marked as IGNORE role
- [x] delete selected: delete the variable selected
- [x] delete missing: delete variables that have any missing values
- [x] delete obs with missing: delete rows that have any missing values.
- [x] For all options confirm first before running the script: are you sure you want to delete this vars ....?

## CONFIG

- [x] The CONFIG widget will have the same options in the Rattle screenshot below.
- [x] The chosen config options determine which R script to run for each chosen variable

## BUILD

- [x] The BUILD button will perform the transformation by running the appropriate R script
- [x] The R scripts update the `ds` with cleaned `ds`
- [x] The SUMMARY page of the dataset is updated to allow further transforms
- [x] The **Dataset** tab shows the new dataset
- [ ] All state variables are updated appropriately

## R Scripts

- [x] There will be different R scripts for each operation
- [x] Scripts will be named as in transform_cleanup_delete_ignored.R.
- [x] The scripts will include parameters to be substituted: 
  - [x] SELECTED_VAR (the original variable name used in all transform_*.R scripts); 

![Image](https://github.com/user-attachments/assets/58b0d341-cb68-42be-8e99-f5ad4ff605d4)

**Comment by yixiangyin** [comment]
It seems that cleanup operation can only be done one at a time in old rattle. Only one operation option can be selected. Is this the case? Do you want this effect or multiple options can be selected to operate.

**Comment by yixiangyin** [comment]
By 'delete ignored', do we delete all the ignored vars no matter whether user selected them or it's done after a transform?

**Comment by yixiangyin** [comment]
" The SUMMARY page of the dataset is updated to allow further transforms"
which page are you referring to?

**Comment by gjwgit** [comment]
Always prompt the user before running the script for these.

## Delete Ignored

`transform_clean_delete_ignored.R`

```
# Remove variables listed in the ignore list.

ds <- ds[ , !(names(ds) %in% IGNORE_VARS)]

```

IGNORE_VARS = `c("location", "date", "min_temp", "sunshine")`

## Delete Selected

`transform_clean_delete_selected.R`

```
# Delete a variable. 

# Remove specific variables from the dataset.

ds$SELECTED_VAR <- NULL
```

## Delete Variables with Missing

`transform_clean_delete_vars_missing.`

The R variable `missing` contains the columns that are missing. We can rExtract that for the user to confirm, and then use the variable `missing` to drop.

Run this command in R:

```
ds <- ds[ , !(names(ds) %in% missing)]
```

The MISSING_VARS is required from flutter so we can clearly inform the user that we will delete these vars.


## Delete Observations with Missing

```
ds <- ds[complete.cases(ds),]
```

**Comment by gjwgit** [comment]
> " The SUMMARY page of the dataset is updated to allow further transforms" which page are you referring to?

No longer relevant. The list of variables for TRANSFORM (i.e., SELECTED) needs to be updated for further transformations.

**Comment by gjwgit** [comment]
> By 'delete ignored', do we delete all the ignored vars no matter whether user selected them or it's done after a transform?

Yes, if a variable has a ROLE of IGNORE then delete it.

**Comment by gjwgit** [comment]
> It seems that cleanup operation can only be done one at a time in old rattle. Only one operation option can be selected. Is this the case? Do you want this effect or multiple options can be selected to operate.

Yes, one transform operation at a time.

**Comment by yixiangyin** [comment]
the update state will be in another issue. It turns out to create extra bugs. 
It seems that after delete the ignored vars and update the state, the last page of dataset tab not working. I will create an issue for that.
