### ISSUE TITLE
RECODE: Implement this TRANSFORM feature

### ISSUE THREAD

**Issue by gjwgit** [gjwgit/rattle#221]
## RECODE:

- [x] Select a variable

If the variable is numeric then: 

- [x] Quantiles
- [x] KMeans
- [x] EqualWidth

These three require a number called BINS. 

- [ ] As Categoric

If the variable is categoric:

- [x] Indicator Variable
- [x] Join Categorics - this requires SELECTED2
- [ ] As Numeric

## CONFIG

- [x] The CONFIG widget will have the same options in the Rattle screenshot below.
- [x] The chosen config options determine which R script to run for each chosen variable
- [x] Need to check compatibility of the script with the variable type (numeric versus categoric)
- [x] The VariableChooser will display suitable variables for the transform

## BUILD

- [x] The BUILD button will perform the transformation by running the appropriate R script
- [x] Business logic include matching selected variable data type to R script data type
- [x] The R scripts update the `ds` with new variables named like XXX_SELECTED_VAR
- [x] The SUMMARY page of the dataset is updated to allow further transforms
- [x] The **Dataset** tab shows the new dataset
- [x] All state variables are updated appropriately
- [x] The transformed variable becomes IGNORE by default but still available to be selected here
- [ ] The newly created variable becomes INPUT by default 

## R Scripts

- [x] There will be different R scripts for each operation
- [x] Scripts will be named as in transform_recode_quantiles_numeric.R.
- [x] The scripts will include parameters to be substituted: 
  - [x] SELECTED_VAR (the original variable name used in all transform_*.R scripts); 

![Image](https://github.com/user-attachments/assets/59d8ac6d-42ac-481b-b188-7c6151d119d9)

**Comment by gjwgit** [comment]
QUARTILES



![Image](https://github.com/user-attachments/assets/67753480-6997-473a-a37a-1013ffe341a0)


```
# Bin the variable(s) into 4 bins using quantiles.

   ds[["BQBIN_SELECTED_VAR"]] <- binning(ds[["SELECTED_VAR"]], BIN, method="quantile", ordered=FALSE)

```

**Comment by gjwgit** [comment]
KMEANS



![Image](https://github.com/user-attachments/assets/b6a1ab46-8ee5-4f5d-9860-307ea9dd1cff)

```
# Remap variables. 

# Bin the variable(s) into 4 bins using kmeans.

if (building)
{
   set.seed(23456)
  crs$dataset[["BK4_MinTemp"]] <- binning(crs$dataset[["MinTemp"]], 4, method="kmeans", ordered=FALSE)
}

```

**Comment by gjwgit** [comment]
EQUAL WIDTH



![Image](https://github.com/user-attachments/assets/9fd573a9-8f85-424b-ab1f-7521a1633b4c)


```
# Bin the variable(s) into 4 bins using equal widths.

if (building)
{
   crs$dataset[["BE4_MinTemp"]] <- cut(crs$dataset[["MinTemp"]], 4)
}

```

**Comment by gjwgit** [comment]
INDICATOR



![Image](https://github.com/user-attachments/assets/1d0c6424-4fb5-4de1-8175-4e1897d4c58f)

```
# Remap variables. 

# Turn a factor into indicator variables.

  crs$dataset[, make.names(paste("TIN_WindGustDir_", levels(crs$dataset[["WindGustDir"]]), sep=""))] <- diag(nlevels(crs$dataset[["WindGustDir"]]))[crs$dataset[["WindGustDir"]],]
```

**Comment by gjwgit** [comment]
JOIN CATEGORIC

This needs the choice of 2 variables.

```
# Turn two factors into one factor.

  ds[, "TJN_SELECTED_SELECTED2"] <- interaction(paste(ds[["SELECTED"]], "_",ds[["SELECTED2"]], sep=""))
  ds[["TJN_SELECTED_SELECTED2"]][grepl("^NA_|_NA$", ds[["TJN_SELECTED_SELECTED2"]])] <- NA
  ds[["TJN_SELECTED_SELECTED2"]] <- as.factor(as.character(ds[["TJN_SELECTED_SELECTED2"]]))
```

**Comment by yixiangyin** [comment]
after recoding, what will be the roles for the new variabel and old one?

Should I grey out the chip are not applicable to the selected variable?

**Comment by yixiangyin** [comment]
The script for as numeric and as categoric is missing?

**Comment by gjwgit** [comment]
Let's skip As Categoric and As Numeric for now - we'll have them as a separate task later.
