### ISSUE TITLE
TRANSFORM RESCALE RANKING: Implementation

### ISSUE THREAD

**Issue by gjwgit** [gjwgit/rattle#222]
Add the RANKING feature - a rescaling where the original values are mapped to a sequential rank. Applies to either numeric or categoric.

![Image](https://github.com/user-attachments/assets/65fe1d79-0c53-439b-8866-3e0c7b1257a8)

Into assets/r/transform_rescale_rank.R

```
# The 'reshape' package provides the 'rescaler' function.


# Rescale SELECTED.

ds[["RRK_SELECTED"]] <- ds[["SELECTED"]]

# Convert values to ranks.

ds[["RRK_SELECTED"]] <-  reshape::rescaler(ds[["SELECTED"]], "rank")
```

**Comment by yixiangyin** [comment]
It seems that rank is just another chip to add. The script has `building`. What is it? Can you get the script ready? Thanks.
