### ISSUE TITLE
TRANSFORM RESCALE INTERVAL: Implementation

### ISSUE THREAD

**Issue by gjwgit** [gjwgit/rattle#223]
![Image](https://github.com/user-attachments/assets/82786371-346a-4ff4-b4b3-b6173286d394)

File transform_rescale_interval.R

```
# The 'reshape' package provides the 'rescaler' function.

library(reshape, quietly=TRUE)

# Rescale MinTemp.

ds[["RIN_SELECTED_INTERVALS"]] <- ds[["SELECTED"]]

# Rescale to 0-99 within each group.

if (building)
{
  ds[["RIN_SELECTED_INTERVAL"]] <-
    reshape::rescale.by.group(ds[["SELECTED"]], type="irank", itop=INTERVALS)
}
```

**Comment by yixiangyin** [comment]
@gjwgit do you know how to fix this?
![Image](https://github.com/user-attachments/assets/b1090294-24d2-444b-8089-d2f7db1793e5)

**Comment by gjwgit** [comment]
That should be rattle::rescale.by.group

**Comment by gjwgit** [comment]
For the number selector can the field also be editable as well as the up/down arrows changing the number. Also is there an option to long press the arrows to continually update the number?

**Comment by yixiangyin** [comment]
It seem this is only for numeric var?
```
> ds[["RIN_wind_gust_dir_90"]] <-
+     rattle::rescale.by.group(ds[["wind_gust_dir"]], type="irank", itop=90)
Warning messages:
1: In Ops.ordered(x, min(x, na.rm = TRUE)) :
  '-' is not meaningful for ordered factors
2: In Ops.ordered((x - min(x, na.rm = TRUE)), diff(range(x, na.rm = TRUE))) :
  '/' is not meaningful for ordered factors
```

**Comment by yixiangyin** [comment]
<img width="2032" alt="Screenshot 2024-08-04 at 12 36 08" src="https://github.com/user-attachments/assets/7dad0464-1962-4ba6-b1e2-4b7358496d47">
