### ISSUE TITLE
SCRIPT: Save adds an extra '.R'

### ISSUE THREAD

**Issue by gjwgit** [gjwgit/rattle#227]
![Image](https://github.com/user-attachments/assets/c7e70923-3e84-48d2-bd1b-ce005d1c2109)

**Comment by gjwgit** [comment]
And where is it saved? I can't find it. Perhaps give the full path to where the file is saved.

**Comment by zheyxu** [comment]
Made pr https://github.com/gjwgit/rattleng/pull/237
