### ISSUE TITLE
[IMAGE PAGE] Add a new button to popup a window to display the image.

### ISSUE THREAD

**Issue by gjwgit** [gjwgit/rattle#228]
## Description

Add an icon next to the Save icon on the ImagePage to popup the current image file into it's own window, retaining the SAVE button.

![Image](https://github.com/user-attachments/assets/f4d67a33-e0b8-4972-99c7-05b4ee14aa6c)

**Comment by gjwgit** [comment]
Note that the plot is in a file that will be overwritten the next time we build a new plot, possibly with different variables. So the popoout might need to rename the file first, as one possible solution, to some random name within tempDir, and display that so we won't lose the plot after an new one is generated.

**Comment by gjwgit** [comment]
I have added the button/icon. Need to add the onPressed().

**Comment by zheyxu** [comment]
Made pr https://github.com/gjwgit/rattleng/pull/263

![Image](https://github.com/user-attachments/assets/16aaf22d-ce9a-477f-a0e7-cc4a93ff3262)
![Image](https://github.com/user-attachments/assets/bbebbbf9-8a58-41f3-b921-a5956b41a216)

**Comment by gjwgit** [comment]
- [x] The user case that I was thinking: As a user I want to be able to view multiple plots at the same time. Currently I can not. For example, I might go to VISUAL and display the Box Plot for min_temp. But I want to compare this to the Box Plot for max_temp. So I want to view both at the same time. Ideally I would like to have a detached window displaying just the one plot after I top the popup button. Then in the main app I choose another variable, generate a plot and tap the popup. Each popout will also need a save button so I can save the image.

**Comment by gjwgit** [comment]
Re-openning this issue. 

I kept the implementation you have as an expanded view. But we require a popout view as well so the user can have multiple plots visable at a time. Thanks

**Comment by gjwgit** [comment]
- [x] Also, please review the code to re-engineer it to extract the enlarger into its own function/class. See comments in the code.

**Comment by zheyxu** [comment]
Made pr https://github.com/gjwgit/rattleng/pull/274
The image will open the file using the default application associated with its file type.

**Comment by gjwgit** [comment]
Works great on Linux. Not yet working on Windows.

**Comment by zheyxu** [comment]
> Works great on Linux. Not yet working on Windows.

Need to have a test.

**Comment by gjwgit** [comment]
Not sure the best approach for Windows.

**Comment by gjwgit** [comment]
For now - works great on Linux/MacOS. Let's hold this while we figure out a good Windows solution.

**Comment by gjwgit** [comment]
Add a popup Alert on Windows to explain this is not yet functional there.
