### ISSUE TITLE
R SOURCE: Identify the current user and replace USER in R script templates

### ISSUE THREAD

**Issue by gjwgit** [gjwgit/rattle#230]
When completing the templates in `lib/r/source.dart` the TIMESTAMP string replacement, at present, has a fixed string USER. We This task is to replace USER with the current user's username.

![Image](https://github.com/user-attachments/assets/5e486768-2d41-44bd-8627-34082ec59a6f)

The TIMESTAMP is used both in the SCRIPT and in the sub title of many plots.

**Comment by zheyxu** [comment]
Made pr https://github.com/gjwgit/rattleng/pull/323
