### ISSUE TITLE
R SOURCE: Identify the current version and replace VERSION in R script templates

### ISSUE THREAD

**Issue by gjwgit** [gjwgit/rattle#231]
Currently in `lib/r/source.dart` we are setting VERSION to a constant. This task is to get the actual version from pubspec.yaml and use that instead.:

![Image](https://github.com/user-attachments/assets/5e59cad6-76aa-4806-a681-3f6f43472011)

**Comment by zheyxu** [comment]
In R code, there is no 'VERSION'. Thus, code `code = code.replaceAll('VERSION', info.version);` makes no sense.

**Comment by gjwgit** [comment]
There is now - thanks. (assets/r/main.R)

**Comment by zheyxu** [comment]
Made pr https://github.com/gjwgit/rattleng/pull/311
