### ISSUE TITLE
BUG: try and break it

### ISSUE THREAD

**Issue by yixiangyin** [gjwgit/rattle#233]
This issue is the master issue to track where things break.

Create new issues for each problem identified.

**Comment by yixiangyin** [comment]
see #239 
load demo -> go to rescale to rescale the min_temp -> go to visual to select the RRC_min_temp. It shows the page without the graph before you build. After you clicked build, it shows the graphs. The graph is a mess.
For some reason it is treating RRC_min_temp as a categoric variable. It should be numeric.


![Image](https://github.com/user-attachments/assets/b9ad30bd-8d47-4bce-8957-ef905de1ca57)
![Image](https://github.com/user-attachments/assets/086f20a0-421a-425f-9291-aa3ae58f4123)

**Comment by yixiangyin** [comment]
load demo -> go to rescale to rescale the min_temp -> go to visual to select the RRC_min_temp. After you clicked build, it shows the graphs. You go back and reset and load the demo again. click visual build. Final 2 graphs are not shown. The console suggest that selected_var are not reset after reset. 
Every providers should be invalidated after reset

**Comment by yixiangyin** [comment]
load demo -> build wordcloud. gives some errors in the console. Perhaps We should prevent user from doing so by disable the build button of wordcloud for demo. For txt files, we should not enable the transform tab and other model except wordcloud?

See #247 

not showing the tab

**Comment by gjwgit** [comment]
> load demo -> go to rescale to rescale the min_temp -> go to visual to select the RRC_min_temp. After you clicked build, it shows the graphs. You go back and reset and load the demo again. click visual build. Final 2 graphs are not shown. The console suggest that selected_var are not reset after reset. Every providers should be invalidated after reset

It looks like the typesProvider does not list RRC_min_temp and so it gets treated as categoric!!!!

**Comment by yixiangyin** [comment]
load demo, go to the third page. reset, load demo, couldn't go to the next page. but could go to the previous page. seems the dots are not reset and the page number are not reset.

Issue created #248

**Comment by gjwgit** [comment]
> > load demo -> go to rescale to rescale the min_temp -> go to visual to select the RRC_min_temp. After you clicked build, it shows the graphs. You go back and reset and load the demo again. click visual build. Final 2 graphs are not shown. The console suggest that selected_var are not reset after reset. Every providers should be invalidated after reset
> 
> It looks like the typesProvider does not list RRC_min_temp and so it gets treated as categoric!!!!

Fixed in 6.2.30
