### ISSUE TITLE
VIEW DATASET: Need to check there is a dataset loaded before trying to display it

### ISSUE THREAD

**Issue by gjwgit** [gjwgit/rattle#244]
Popup an alert if there is not dataset loaded yet.

**Comment by mukundsrinivasb** [comment]
I would like to start working on this issue. From what I understand , there should be a pop-up when the user tries using other tabs without loading a dataset?

**Comment by gjwgit** [comment]
Thanks @mukundsrinivasb. I just checked each of the features in the EXPLORE and the TRANSFORM tabs. They all warn that no dataset is loaded so I think this one is already done!
