### ISSUE TITLE
DATASET: On a RESET the page navigator is confused

### ISSUE THREAD

**Issue by gjwgit** [gjwgit/rattle#248]
load demo, go to the third page. reset, load demo, couldn't go to the next page. but could go to the previous page. seems the dots are not reset and the page number are not reset.

**Comment by zheyxu** [comment]
Made a pr https://github.com/gjwgit/rattleng/pull/369

**Comment by gjwgit** [comment]
As separately discussed, this issue and PR is purely focused on the navigation (not on the failure of ds glimpse for the large dataset.
