### ISSUE TITLE
BUG/STATE MANAGEMENT: update flutter state as R state changes

### ISSUE THREAD

**Issue by yixiangyin** [gjwgit/rattle#255]
After delete DATE, several providers are not updated including but not limited to group_by and rolesProvider and typesProvider. Group_by causes issues.

![Image](https://github.com/user-attachments/assets/981027a4-3e8a-4996-9980-1529a7ab68d3)

![Image](https://github.com/user-attachments/assets/b88c1e23-2eb7-488c-885d-db3609316b59)

**Comment by gjwgit** [comment]
Has been fixed.
