### ISSUE TITLE
R: Check if R is available and has started on startup

### ISSUE THREAD

**Issue by gjwgit** [gjwgit/rattle#270]
## Description

- [x] On starting up the app we need to check if R is available to Rattle. This might involve using the system command with R or R.exe and if the command fails then R is not installed ot not in the user's path and so we put a popup to say this then exit the app.
- [x] If R is found but the console does not seem to start up with R as expected (check for the string 'R version' at the beginning of stdout provider) then issue a popup to say 'R was not started. Please check the COosole tab for errors.' Don't exit but we won't be able to do anything else.

**Comment by junhaow1** [comment]
![Image](https://github.com/user-attachments/assets/bd8236d3-c335-43e4-bcd0-ea1ec7c592f0)

**Comment by junhaow1** [comment]
![Image](https://github.com/user-attachments/assets/73f311d3-a72b-4a9c-948f-6c9ef977d89a)

**Comment by junhaow1** [comment]
https://github.com/gjwgit/rattleng/pull/592 PR created
