### ISSUE TITLE
[WINDOWS] The version number is not shown on Windows

### ISSUE THREAD

**Issue by gjwgit** [gjwgit/rattle#273]
On Linux I see the version number top right:

![Image](https://github.com/user-attachments/assets/9b2f09e8-d1a1-4915-aaea-70728d7c165b)

On Windows I see 1.0.0:

**Comment by Lutra-Fs** [comment]
https://github.com/flutter/flutter/issues/73652 known issue.
**If your project was created before Flutter 3.3 you need to migrate the project according to [this guide] (https://docs.flutter.dev/release/breaking-changes/windows-version-information)**
Will create a PR this evening
