### ISSUE TITLE
IMPUTE: Review and grey out transforms that are not supported

### ISSUE THREAD

**Issue by gjwgit** [gjwgit/rattle#282]
For IMPUTE if I choose a categoric variable then MEAN, MEDIAN, and MODE should be greyed out - not active.

**Comment by gjwgit** [comment]
Actually - MODE is okay for categoric variables.

**Comment by gjwgit** [comment]
Was this tested???? 

- [x] When first variable is categoric the greying does not  show.
- [x] When MEAN or MEDIA N is selected and change variable to a CATEGORIC the MEAN/MEDIAN remains selected and even attempted!!!
- [x] MODE is supported for NUMERIC and CATEGORIC

**Comment by yixiangyin** [comment]
> Was this tested????
> 
>     * [ ]  When first variable is categoric the greying does not  show.
> 
>     * [ ]  When MEAN or MEDIA N is selected and change variable to a CATEGORIC the MEAN/MEDIAN remains selected and even attempted!!!
> 
>     * [ ]  MODE is supported for NUMERIC and CATEGORIC

> When first variable is categoric the greying does not show.
what have you done to produce this?

**Comment by gjwgit** [comment]
Examples:

Loading the file `intergration_test/rattle_test_large.csv`, then go into TRANSFORM -> IMPUTE

![Image](https://github.com/user-attachments/assets/bdf7c446-01a4-4fda-8c5a-e9dbe961ae38)

For DEMO, in IMPUTE I chose MEAN for sunshine then I chose wind_gust_dir - but it should not stay with MEAN - perhaps go back to the default ZERO/MISSING.

![Image](https://github.com/user-attachments/assets/7104277f-f3d2-4a8f-92c4-75e4a3453c6c)

**Comment by gjwgit** [comment]
Tested - all working. Thanks.
