### ISSUE TITLE
DEBUG: Summary freezes

### ISSUE THREAD

**Issue by gjwgit** [gjwgit/rattle#286]
## To Debug

1. Load rattle_test_large.csv
2. EXPLORE -> SUMMARY freezes

**Comment by gjwgit** [comment]
Need to investigate why it gets stuck after the third page - the forth dot does not appear even after 10 minutes. Cannot tap to CONSOLE (or anywhere else) to see. CPU is 100%.

By design there is no large data going into flutter - R is consuming lots of CPU with rattle the rest.

![Image](https://github.com/user-attachments/assets/803daf77-7235-4d86-b917-a8a2d2c19ee5)

**Comment by gjwgit** [comment]
The forth page is Hmisc::describe() - repeat on R command line to see if that is the problem. If so, drop Hmisc::describe as not providing any extra insight.

Hmisc::descibe is just fine in R

**Comment by zheyxu** [comment]
> The forth page is Hmisc::describe() - repeat on R command line to see if that is the problem. If so, drop Hmisc::describe as not providing any extra insight.
> 
> Hmisc::descibe is just fine in R

Hi @gjwgit, the commend `Hmisc::describe(ds)` has on problem in Mac. And it takes about 1 min for the app to response.

**Comment by gjwgit** [comment]
So it might be the next command in the queue! Perhaps save the R script for DEMO and replace the weather dataset with the test dataset then run the R script

**Comment by zheyxu** [comment]
> So it might be the next command in the queue! Perhaps save the R script for DEMO and replace the weather dataset with the test dataset then run the R script

Hi @gjwgit, the command `Hmisc::contents(ds)` takes most of processing time. `Hmisc::describe(ds)` is quick.

To replace the weather dataset with the test dataset, it should modify the rattle project. The flutter app does not load dataset from `assets/data` folder.

**Comment by zheyxu** [comment]
Link with issue https://github.com/gjwgit/rattleng/issues/298

**Comment by gjwgit** [comment]
I am exploring.

**Comment by gjwgit** [comment]
Dropping the Hmisc functions and probably CrossTab - my machine runs out of memory.

**Comment by gjwgit** [comment]
Original version of Rattle also does not complete Summary with all options enabled.

- [ ] Perhaps add new issue to toggle inclusion of   SKIM + SUMMARY + SPREAD + CROSS TAB only. Any number can be chosen with SKIM as the default.
