### ISSUE TITLE
TEXT PAGE: Support horizontal scrolling

### ISSUE THREAD

**Issue by gjwgit** [gjwgit/rattle#288]
I plan to make the R output wider by default (120 perhaps instead of 80).

This will mean the TextPage will wrap the output and it looks ugly!

Implement TextPage so we can horizontally scroll.

**Comment by junhaow1** [comment]
demo: 
https://github.com/user-attachments/assets/efef4b69-e55f-4b52-b181-7f8fcb45346a

**Comment by junhaow1** [comment]
PR created https://github.com/gjwgit/rattleng/pull/307

**Comment by gjwgit** [comment]
Thanks @junhaow1. Is there a horizontal scrollbar option like the vertical scrollbar on the right hand side here:



![Image](https://github.com/user-attachments/assets/f3d81cc0-ac8e-46ec-b868-a75e53ae458e)

**Comment by junhaow1** [comment]
demo:

https://github.com/user-attachments/assets/28e9803f-2919-44fa-9751-7f7dd290f94f

**Comment by junhaow1** [comment]
-  Scrollbar: This widget wraps the SingleChildScrollView to display a horizontal scrollbar.
- isAlwaysShown: true: This makes sure the scrollbar is always visible.




https://github.com/gjwgit/rattleng/pull/325 PR created
