### ISSUE TITLE
CONSOLE: Support copy and paste

### ISSUE THREAD

**Issue by gjwgit** [gjwgit/rattle#291]
## Description

Currently copy and paste do not work in the CONSOLE. It is essential we get this working.

## Why

We need to be able to past "fixes" into the R process and copy stuff from there to share or capture for bug reports, for example.

**Comment by zheyxu** [comment]
Made pr https://github.com/gjwgit/rattleng/pull/310
User can copy and paste.

![Image](https://github.com/user-attachments/assets/2001d531-3e9b-4925-8e94-ad89c2547f20)
