### ISSUE TITLE
BUG: Load a second dataset does not properly reset

### ISSUE THREAD

**Issue by gjwgit** [gjwgit/rattle#294]
## To Repeat

+ Start Rattle
+ Load DEMO
+ Load rattle_test_large.csv
+ Note that rec_id, ssn, medicare_number are not IDENT

A fresh start and load rattle_test_large:

![Image](https://github.com/user-attachments/assets/0f8c1bf8-9511-4f8e-99cd-d2543aee4ad0)

After DEMO then load rattle_test_large

![Image](https://github.com/user-attachments/assets/3061b865-79f7-40a7-8643-ee62cb374f92)

TARGET gets set okay.

![Image](https://github.com/user-attachments/assets/ee17d3a3-7ebe-4b6a-9cd8-8905ca8881fc)

**Comment by gjwgit** [comment]
Part of the problem is probably that the providers are not fully being reset to match the new dataset. After a fresh start, then DEMO, then FILENAME rattle_test_large.csv I see the following values for the providers. Related to #253 

![Image](https://github.com/user-attachments/assets/499d80e7-623f-42f0-941f-12e3e4e8e9aa)

ROLES is missing and TYPES are for the DEMO dataset, not the rattle_test_large dataset!

**Comment by yixiangyin** [comment]
#376

**Comment by gjwgit** [comment]
Closing this - the scenario described is now functional.
