### ISSUE TITLE
ROLES: TARGET should default to the factor with least number of levels

### ISSUE THREAD

**Issue by gjwgit** [gjwgit/rattle#295]
## Description

The rules for identifying TARGET need work. On loading the rattle_test_large dataset the  TARGET should be gender, not the last variable. Gender is chosen because it is a categoric and it has the feweset number of levels (no TARGET should have more than 5 levels). The final variable is not really categoric and it mas way too many levels.

`lib/features/dataset/display.dart`

**Comment by zheyxu** [comment]
Find a bug https://github.com/gjwgit/rattleng/issues/320 related to this issue.
