### ISSUE TITLE
SCRIPT: Please use a file/folder navigator to save the script.R file

### ISSUE THREAD

**Issue by gjwgit** [gjwgit/rattle#297]
## Description

Currently on SAVE a script it defaults to the current working directory and the default name `script.R` which is good

To specify a different location I have to type in the path.

This task is to use the standard OS file chooser to be able to navigate to a folder, to be given the default file name of `script.R` and to be able to change the filename.

**Comment by Lutra-Fs** [comment]
Maybe I could work on this one at this weekend. 😄
