### ISSUE TITLE
VISUAL: Default variable should be the first numeric variable

### ISSUE THREAD

**Issue by gjwgit** [gjwgit/rattle#299]
## Description

EXPLORE -> SUMMARY -> VARIABLE should default to the first numeric variable if there are any and then to the first variable if no numeric variables. Currently it defaults to the first INPUT variable.

**Comment by zheyxu** [comment]
![Image](https://github.com/user-attachments/assets/64964b1d-53b6-462d-88e6-0738d7f1f5db)
