### ISSUE TITLE
DATASET: Page Dot Indicator Not Updating on Horizontal Scroll in DataSet Page

### ISSUE THREAD

**Issue by junhaow1** [gjwgit/rattle#300]
## Description
Fix the issue where the page dot indicator at the bottom of the DataSet page does not update when scrolling horizontally using a trackpad. The page dots are intended to reflect the current page being viewed, but currently, when users scroll left or right through the pages, the page dot UI remains static, leading to confusion about which page is currently displayed. The UI should be responsive to trackpad gestures, ensuring that the page dots accurately represent the current page at all times.

## Why
The page dot indicator serves as a visual guide for users, showing them which page they are currently viewing within the DataSet page. When this indicator fails to update with horizontal scrolling, it can confuse users, disrupting their navigation experience. Ensuring that the page dots accurately reflect the current page status is essential for maintaining a seamless and intuitive user experience, especially for those navigating through large datasets.

## Closing Criteria

- [x]  The page dot indicator updates correctly when scrolling horizontally using a trackpad.

- [x]   The page dot UI consistently reflects the current page being viewed, regardless of the scrolling method used.

**Comment by junhaow1** [comment]
![Image](https://github.com/user-attachments/assets/26f34928-eabd-4df5-87b7-9d417c7876cc)

**Comment by junhaow1** [comment]
![Image](https://github.com/user-attachments/assets/ace3fb59-ba46-4528-9886-981594af4117)

**Comment by gjwgit** [comment]
I also notice various other times (like a rebuild) when the dots get out of sync. Probably related and the implementation an/or usage could do with a review.

**Comment by junhaow1** [comment]
demo: 

https://github.com/user-attachments/assets/a5f13c9b-9e00-4250-b826-b9fb746d1d68

**Comment by junhaow1** [comment]
PR created https://github.com/gjwgit/rattleng/pull/308

**Comment by junhaow1** [comment]
Reason for this bug: `TabController` and `TabPageSelector` not being updated accordingly. 

Solution:   synchronize the `PageView`'s page changes with the `TabController` so that the `PageIndicator` updates correctly.

**Comment by gjwgit** [comment]
Excellent - thanks for the explanation.
