### ISSUE TITLE
DATASET: Null Check Operator Error on Third Page of DataSet When Importing rattle_test_large.csv

### ISSUE THREAD

**Issue by junhaow1** [gjwgit/rattle#301]
## Description
Address the issue where a red screen error (Null Check Operator Error) occurs on the third page of the DataSet after importing the rattle_test_large.csv file from a local device. This error disrupts the user's ability to view and interact with the data, as the page fails to load properly and displays an error instead. The error seems to be related to a null value that isn't being properly checked or handled within the code, particularly when the dataset is large and the user navigates to the third page.

## Why
Ensuring that users can successfully import and navigate through large datasets is crucial for the functionality of the DataSet page. The presence of a Null Check Operator Error not only prevents users from accessing their data but also undermines the reliability of the platform. Fixing this issue is essential for maintaining a smooth user experience, especially for users working with large datasets. Properly handling null values in the code will prevent such errors and improve the overall stability and robustness of the platform.

## Closing Criteria

- [ ]  The Null Check Operator Error is resolved, and the third page of the DataSet loads correctly after importing rattle_test_large.csv.

- [ ]   Users can navigate through all pages of the DataSet without encountering red screen errors.

**Comment by junhaow1** [comment]
![Image](https://github.com/user-attachments/assets/dee9c0f8-2c2d-462f-9dd5-49264df84e3d)

**Comment by gjwgit** [comment]
I don't see this on Linux with 6.2.52. Could you try on the current dev. Thanks.
