### ISSUE TITLE
RESCALE: Layout affected by ChoiceChipTip change

### ISSUE THREAD

**Issue by gjwgit** [gjwgit/rattle#303]
Please restore the ChoiceChip layout for RESCALE. 

The layout of RESCALE now looks like this:

![Image](https://github.com/user-attachments/assets/eb361ba4-a4c3-4a81-8574-27789249627b)

It used to look like this:

![Image](https://github.com/user-attachments/assets/d84e4fc6-78c3-4ce0-9311-9c711da96108)

**Comment by zheyxu** [comment]
Hi @gjwgit, there are two designs, please choose one. Currently choose the second design.



![Image](https://github.com/user-attachments/assets/f8f520b4-6d68-404d-90de-07ad4e688476)
![Image](https://github.com/user-attachments/assets/b13bd445-7e0d-4bc6-b58a-6d5f1873b761)

**Comment by zheyxu** [comment]
Made pr https://github.com/gjwgit/rattleng/pull/306
