### ISSUE TITLE
TESTING: Load DEMO and Confirm GLIMPSE and ROLES pages

### ISSUE THREAD

**Issue by gjwgit** [gjwgit/rattle#309]
## Description

Mimic DATASET -> DEMO -> Navigate to GLIMPSE (Page 2)
, 
Confirm Glimpse contains for example, "1019.7", "2007-11-01".

Basically, how much of my original code in the current app_test.dart can be got to work now after all our changes.

**Comment by junhaow1** [comment]
PR created https://github.com/gjwgit/rattleng/pull/347

**Comment by gjwgit** [comment]
PR covers EXPLORE tab. This was to cover DATASET tab (GLIMPSE and ROLES)?
