### ISSUE TITLE
BUG: load dataset 2 after load dataset 1 raises issue

### ISSUE THREAD

**Issue by zheyxu** [gjwgit/rattle#320]
# Description
To reproduce:

1. load demo dataset
2. load large test dataset
3. raises issues in console and the app cannot recognise `Ident` and `Risk` and `Target` correctly.

![Image](https://github.com/user-attachments/assets/789765a7-fb2c-4c79-b981-ab787c47b026)
![Image](https://github.com/user-attachments/assets/adb67046-653c-41b2-a2f1-00cffc461e58)
The issue is related to #295

**Comment by gjwgit** [comment]
I've seen this at times too and can replicate it.

I suspect it's an async issue again. Somehow we need to check with the console each time we run a script (through rSource) to make sure the previous script has finished running - not sure how we can do that.

**Comment by gjwgit** [comment]
Closing this now. The scenario has been fixed.
