### ISSUE TITLE
VISUAL: Do not allow GROUP BY with more than 20 levels

### ISSUE THREAD

**Issue by gjwgit** [gjwgit/rattle#329]
For the GROUP BY do not list any categoric variables with more than 10 categories.

![Image](https://github.com/user-attachments/assets/edc95bfc-6f19-4ad4-920a-6067adf3a0d3)

**Comment by gjwgit** [comment]
Once we introduce character types then simply list all factors here again since the suer may override factor/character typpes in ROLES.

**Comment by gjwgit** [comment]
If variables with > 20 levels are auto IGNORED, then perhaps this issue becomes mute - once issue #404 resolve, decide what to do here.

**Comment by zheyxu** [comment]
Made pr https://github.com/gjwgit/rattleng/pull/439
<img width="1244" alt="Screenshot 2024-09-20 at 1 14 05 pm" src="https://github.com/user-attachments/assets/6c32471b-f172-45c9-8888-f738e575cc23">

**Comment by zheyxu** [comment]
Currently have not find a way to test the Dropdown menu widget, thus the integration test does not cover the page in screenshot.

**Comment by gjwgit** [comment]
Thanks. 

- [ ] Once you have a screenshot of the output all successful `make qtest.tmp` we can merge this.

**Comment by gjwgit** [comment]
Once we found a way to get the list of variables in the DropDown then the test will be:

- [ ] Load LARGE dataset
- [ ] EXPLORE -> VISUAL -> GROUP BY - variables are gender (default), state, marital status.
- [ ] DATASET -> ROLES -> IGNORE state
- [ ] EXPLORE -> VISUAL -> GROUP BY - variables are gender (default), marital status.

**Comment by zheyxu** [comment]
Link to integration test result: https://github.com/gjwgit/rattleng/pull/439#issuecomment-2365466714
