### ISSUE TITLE
SUMMARY: Add checkbox for Cross Tab

### ISSUE THREAD

**Issue by gjwgit** [gjwgit/rattle#331]
## Description

For the SUMMARY feature add toggles for the inclusion of SUMMARY + SKIM + SPREAD + CROSS TAB. 
 
Any number can be chosen with All but CROSS TAB as the default. CROSS TAB can be very expensive.

Use the FilterChip but with the same colour choices and Tooltip option as ChoiceChipTip

**Comment by junhaow1** [comment]
https://github.com/gjwgit/rattleng/tree/kev/331_summary 
working branch

**Comment by junhaow1** [comment]
<img width="1045" alt="image" src="https://github.com/user-attachments/assets/a48fc5c1-35d4-480c-80cb-e0e9c7583e07">
<img width="693" alt="image" src="https://github.com/user-attachments/assets/8a8e91e7-bd3c-41ec-88cc-c08ea4876d00">

**Comment by junhaow1** [comment]
https://github.com/gjwgit/rattleng/pull/504 PR created

**Comment by junhaow1** [comment]
demo video: 
https://github.com/user-attachments/assets/054ba514-2371-4f67-b520-f7bbdb986fff

**Comment by gjwgit** [comment]
**UPDATE** Change of plan! Let's remove the chips and add a check box to specify whether to include CrossTab. Let's revert to a single explore_summary.R file.

**Comment by junhaow1** [comment]
demo video: https://github.com/user-attachments/assets/6f2c3fd1-f2e2-4c3d-8d73-9b5e24d93e29

**Comment by junhaow1** [comment]
> **UPDATE** Change of plan! Let's remove the chips and add a check box to specify whether to include CrossTab. Let's revert to a single explore_summary.R file.

on it

**Comment by junhaow1** [comment]
https://github.com/gjwgit/rattleng/pull/510 PR created

**Comment by junhaow1** [comment]
demo video : 
https://github.com/user-attachments/assets/c449c54c-8ad4-4417-8a2c-11f77d71b7ee

**Comment by gjwgit** [comment]
Just the single check button looks great. Thanks.

**Comment by junhaow1** [comment]
Demo: 
https://github.com/user-attachments/assets/68e51f29-9f24-46ab-a54e-89adb02a73a2

**Comment by junhaow1** [comment]
https://github.com/gjwgit/rattleng/pull/510 PR created
