### ISSUE TITLE
NUMBER FIELD: Embed label in border like DropdownMenu

### ISSUE THREAD

**Issue by gjwgit** [gjwgit/rattle#334]
## Description

The embedding of the label within the box border saves on space being used above the box, and also is consistent wit the DropdownMenu variable selectors.

This task is to update the NumberField widget to embed the label in the boxjust like the 'Variable' in the DropdownMenu here:

![Image](https://github.com/user-attachments/assets/e2b1d253-29d8-47d7-b276-98499d4fe634)

## So That

We retain a consistent style for the entry boxes (numeric or variable selection) and not surprise the suer with the inconsistency.

**Comment by zheyxu** [comment]
Made pr https://github.com/gjwgit/rattleng/pull/371


![Image](https://github.com/user-attachments/assets/f145f890-427b-4b84-babb-6cce8e527bc2)
