### ISSUE TITLE
TESTING: Demo/Large Explore Missing

### ISSUE THREAD

**Issue by gjwgit** [gjwgit/rattle#341]

**Comment by junhaow1** [comment]
https://github.com/gjwgit/rattleng/pull/367 PR created

**Comment by junhaow1** [comment]
- [x]  large 

<img width="1368" alt="image" src="https://github.com/user-attachments/assets/9c21f0de-5650-481d-81a4-d8048934f5fe">



- [x]  demo 

<img width="1303" alt="image" src="https://github.com/user-attachments/assets/656477af-8392-485e-a29e-4e02adc0be62">

**Comment by junhaow1** [comment]
**1. Helper Functions:**

- _openDemoDataset: Handles the steps to open the demo dataset.

- _navigateToExploreTab: Handles navigation to the Explore tab.
- _navigateToTab: Handles navigation to a specific tab by title and verifies the panel type.
- _performMissingAnalysis: Handles the steps for performing the missing analysis.
- _verifyPageContent: Handles the verification of specific content on the analysis pages.

**2. Parameterization:**

The _navigateToTab and _verifyPageContent functions are parameterized to allow flexibility in navigating to different tabs and verifying different content.

**3. Reduction of Repetition:**

By using these helper functions, the main test body is much cleaner, and the repeated logic is centralized in one place.

**Comment by gjwgit** [comment]
Excellent to use helper functions. One more to move into utils! Once moved we can close this.

**Comment by junhaow1** [comment]
> Excellent to use helper functions. One more to move into utils! Once moved we can close this.

Hi @gjwgit the functions have been moved to utils in the last PR 
<img width="538" alt="image" src="https://github.com/user-attachments/assets/f1609135-c345-4ffe-bdfc-709263713edb">

**Comment by gjwgit** [comment]
I don't see the PR with helper moved into utils? Looking for navigate_to_tab and navigate_to_feature.

**Comment by junhaow1** [comment]
PR merged , can be closed
