### ISSUE TITLE
TESTING: Demo/Large Explore Correlation

### ISSUE THREAD

**Issue by gjwgit** [gjwgit/rattle#342]

**Comment by junhaow1** [comment]
- [x] large 
<img width="1208" alt="image" src="https://github.com/user-attachments/assets/7e74c3e1-50bb-49e7-9734-8c0fb8209d70">


- [x] demo 
<img width="1180" alt="image" src="https://github.com/user-attachments/assets/c3ae6845-f92f-4fda-88d7-334942fafef9">

**Comment by junhaow1** [comment]
https://github.com/gjwgit/rattleng/pull/372 PR created
