### ISSUE TITLE
TESTING: Demo/Large Transforms

### ISSUE THREAD

**Issue by gjwgit** [gjwgit/rattle#344]

**Comment by junhaow1** [comment]
- [x] demo

<img width="1115" alt="image" src="https://github.com/user-attachments/assets/21a44aab-b2af-439c-be2d-1874169a0472">

- [x] large 

<img width="1104" alt="image" src="https://github.com/user-attachments/assets/a710bced-fdea-4327-9d60-8606c822ca36">

**Comment by junhaow1** [comment]
https://github.com/gjwgit/rattleng/pull/402 PR created
