### ISSUE TITLE
TESTING: Test deletion of IGNOREd

### ISSUE THREAD

**Issue by gjwgit** [gjwgit/rattle#356]
## Description

Add a test `integration_test/cleanup_ignore_demo_test.dart` to do the following

- [x] Load the DEMO dataset
- [x] Choose the first 4 variables to ignore
- [x] On TRANSFORM -> CLEANUP choose IGNORED and tap DELETE FROM DATASET
- [x] Tap YES on the warning
- [x] Go to the next page and confirm that the variables are **not** listed.
- [x] Go to EXPLORE -> VISUAL and confirm the deleted variables are not listed as available 
- [x] Check that `evaporation` is the SELECTED Variable

What else to test to ensure the deletion has bee successfully accomplished?

Might want to test this scenario as it is currently failing, continuing from the above steps

- [x] Go to DATASET -> ROLES and choose the next 2 variables to delete
- [x] Go to TRANSFORM -> CLEANUP -> IGNORED and DELETE
- [x] Go to EXPLORE -> VISUALISE and expect wind_gust_speed as the default SELECTED

**Comment by yixiangyin** [comment]
what is failing?

**Comment by yixiangyin** [comment]
@gjwgit Thanks for the feedback. The cause of the bug is that the selected provider is not checked when we delete variables. I have add some code to check both selected and selected2 providers.

**Comment by gjwgit** [comment]
Looks great. Thanks for the tests.
