### ISSUE TITLE
ROLE: Allow the user to select multiple variables to set ROLE in one go

### ISSUE THREAD

**Issue by gjwgit** [gjwgit/rattle#374]
## Description

A very useful feature of Rattle V5 was to be able to highlight multiple variables/rows in the ROLE feature/table and then make them all IGNORE or INPUT with a single click of the INPUT/IGNORE button in the config panel.

This task is to implement similar functionality in RattleNG?

Here is Rattle V5. I have Shift-Selected multiple rows in the table

![Image](https://github.com/user-attachments/assets/0d1a3eff-a9e1-4dad-b2b0-6bd8454b718a)

After I tap the IGNORE buton (the INPUT and IGNORE buttons are named as such in the left bottom of the congif area) I get the following update of the variable roles.

![Image](https://github.com/user-attachments/assets/71112b21-8d47-4b0d-8538-86bec3fb6b3f)

We want this behaviour in RattleNG

**Comment by junhaow1** [comment]
the standard behaviour is something like:
 

- [x] if I tap a row it should get highlighted. Any other row(s) that was highlighted should no longer be highlighted.

- [ ] If I tap a row and hold my mouse down then move the mouse over other rows then they all get selected/highlighted until I let go of the mouse button.
- [x] If I tap a row, it get highlighted. If I tap another row while holding the shift key then that row gets highlighted without the original row getting un-highlighted

**Comment by junhaow1** [comment]
Allow shift select multiple rows 
![Image](https://github.com/user-attachments/assets/be8b07f7-02d7-47a8-9d1b-e102fd575e95)

**Comment by junhaow1** [comment]
demo video :
https://github.com/user-attachments/assets/c86b7d98-8936-4744-bfe0-01d7ca5b9dcc

**Comment by junhaow1** [comment]
https://github.com/gjwgit/rattleng/pull/577 PR created

**Comment by junhaow1** [comment]
![image](https://github.com/user-attachments/assets/186fc4a3-5291-4c0c-8345-d533ef8a750f)
