### ISSUE TITLE
BUG in Providers: load the demo and then load the large dataset

### ISSUE THREAD

**Issue by yixiangyin** [gjwgit/rattle#376]
load demo, reset, load large dataset, move to debug. 

It seems that if we move away from the dataset tab too quickly, the roles provider and types provider might not be set for the large dataset.  This seems to be a seperate issue on its own #377 
![Image](https://github.com/user-attachments/assets/840e9079-108c-421e-9838-78e4c278f3ce)
Then if I try to reset again, app freezes.

If we wait for a bit and move to debug, we see abnormal providers.

![Image](https://github.com/user-attachments/assets/99ae25e0-8dc7-404f-88ea-ec00ef57a80c)
![Image](https://github.com/user-attachments/assets/7ca7def6-44ef-43d4-a363-4ddc2d8a6ab8)

**Comment by gjwgit** [comment]
Thanks. This looks to be very problematic. Could it be resolved by blocking the GUI while the R scripts are running? As in https://github.com/gjwgit/rattleng/issues/298 and https://github.com/gjwgit/rattleng/issues/212
