### ISSUE TITLE
BUG: moving away from large dataset fast leaves roles provider uninitialised

### ISSUE THREAD

**Issue by yixiangyin** [gjwgit/rattle#377]
move to debug after loading the dataset

![Image](https://github.com/user-attachments/assets/daa9fe5c-dfd9-46b6-89d0-406ccaf1c7f5)

**Comment by gjwgit** [comment]
Thanks for noting the issue.

I can not replicate it on the rattle_test_20k.csv dataset but can on rattle_test_100k.csv - depends on how quickly the app can load the dataset.

I think it is related to #298 and #212

Once the data set has been loaded all looks okay again in DEBUG? But not according to #376 which has an issue with the move from DATASET which is when the ROLES are set up. That is a problem - can see it now and also related to allowing the user to move around the GUI while a script is running.

**Comment by gjwgit** [comment]
Could this be set up as a test that demonstrates the issue and then will be OK once the issue is fixed? Thanks.
