### ISSUE TITLE
BUG: Fix dataset_reset_test to properly load the 20k dataset.

### ISSUE THREAD

**Issue by gjwgit** [gjwgit/rattle#378]
Currently the 20k dataset is not being properly loaded. Fix it so that it is properly loaded after a RESET. It loads just fine on a app startup.

**Comment by zheyxu** [comment]
Made pr https://github.com/gjwgit/rattleng/pull/380 and the test already exists.

**Comment by gjwgit** [comment]
PR #380 works to fix the large dataset load after a reset.
