### ISSUE TITLE
TEMPDIR: Remove tempdir on leaving the app

### ISSUE THREAD

**Issue by gjwgit** [gjwgit/rattle#379]
## Description

Each time rattle runs it creates a tempdir (on Linux as /tmp/rattleXXXXXX/). R also creates a tmpdir (/tmp/RtmpXXXXX/).

These hang around until the computer reboots.

On exit from rattle this task is to remove these temporary dictories.

**Comment by Lutra-Fs** [comment]
Given the unpredictable nature of application closing, especially on Windows, I wonder if it might be more reliable to clean up the previous temp directories when starting RattleNG, rather than on exit. From my understanding, there isn't a completely dependable way to register a closing callback on Windows that would work in all scenarios.
A startup cleanup process could potentially:

- Run consistently regardless of how the previous session ended
- Handle cases of multiple instances or improper closures
- Work across different operating systems without relying on exit behaviours

Of course, we'd need to carefully consider things like naming conventions for the temp directories and ensuring we don't remove directories still in use.
I'm very interested in your thoughts on this approach.

**Comment by gjwgit** [comment]
There is often a callback available for when a application exists by any means though I am not familiar with the issues for Windows. This would be a good location to remove the tempDir and might work most of the time.

A problem with doing it on startup could be that another instance of Rattle could also be running and we don't want to delete its tempDir!

ChatGPT suggests the following. Could be worth experimenting.

```
In Flutter you can detect when the application is being terminated or exited by using lifecycle events. Specifically, the AppLifecycleState.detached state can help detect when the app is being terminated.

Here’s how you can handle lifecycle changes in a Flutter app:

Override the didChangeAppLifecycleState method: You can listen to the app’s lifecycle changes by using the WidgetsBindingObserver mixin in your widget.

Detect the AppLifecycleState.detached state: This state corresponds to the point when the app is no longer visible and about to be destroyed.

Here’s an example:

import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatefulWidget {
  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> with WidgetsBindingObserver {
  @override
  void initState() {
    super.initState();
    WidgetsBinding.instance.addObserver(this);  // Add observer for lifecycle changes
  }

  @override
  void dispose() {
    WidgetsBinding.instance.removeObserver(this);  // Remove observer when the widget is disposed
    super.dispose();
  }

  @override
  void didChangeAppLifecycleState(AppLifecycleState state) {
    if (state == AppLifecycleState.detached) {
      // App is exiting
      print('App is exiting');
      // Perform necessary cleanup or saving of state here
    }
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(title: Text('Flutter App Exit Callback')),
        body: Center(child: Text('Home Page')),
      ),
    );
  }
}

Explanation:

AppLifecycleState.detached: This state is triggered when the app is detached from the host and is in the process of being destroyed.

The WidgetsBindingObserver allows you to observe lifecycle changes in your app, including when it is exiting.

Keep in mind that AppLifecycleState.detached may not always be fired in some environments (e.g., Android or iOS), depending on how the app is terminated.
```

**Comment by Lutra-Fs** [comment]
Tested Observer, seems not working on Windows.

https://github.com/leanflutter/window_manager#confirm-before-closing is an interesting approach.

**Comment by gjwgit** [comment]
Looks good. Tested on Linux. /tmp/rattleXXXXXX is removed.

![image](https://github.com/user-attachments/assets/4b9d68ec-3c3a-4792-bcad-0be2b468d5c4)

**Comment by gjwgit** [comment]
On Linux it seems that there is both `/tmp/rattlengXXXXXX/` and `/tmp/rattleXXXXXX`. I create the latter for the app, but where is the former coming from? Is it automatically created by Flutter? Does this also happen on Windows @Lutra-Fs  and MacOS @zheyxu?

**Comment by Lutra-Fs** [comment]
> On Linux it seems that there is both `/tmp/rattlengXXXXXX/` and `/tmp/rattleXXXXXX`. I create the latter for the app, but where is the former coming from? Is it automatically created by Flutter? Does this also happen on Windows @Lutra-Fs and MacOS @zheyxu?

`rattlengxxx` folder is internally used by flutter in the build process. I believe those folders will not be generated in the production version.

> From Claude:
A dill file in the context of Flutter is a compiled intermediate representation of Dart code. Here's a brief explanation of what dill files are and their purpose:

> Definition:
DILL stands for "Dart Intermediate Language Layer". It's a file format used by the Dart VM (Virtual Machine) and Flutter.
Purpose:

> Dill files contain a serialized version of Dart's internal AST (Abstract Syntax Tree) and kernel AST.
They serve as an intermediate step between Dart source code and machine code.


> Usage in Flutter:

> When you build a Flutter app, the Dart compiler generates dill files as part of the compilation process.
These files are used to speed up subsequent builds and hot reloads.


> Benefits:

> Faster compilation: Dill files allow for incremental compilation, which means only changed parts of the code need to be recompiled.
Improved hot reload performance: The Dart VM can quickly load and execute dill files, enabling fast hot reloads during development.


> Location:
In a Flutter project, you can typically find dill files in the build directory, often under .dart_tool/flutter_build.
File extension:
Dill files usually have the .dill extension.

> Dill files are generally not something you need to interact with directly as a Flutter developer, but understanding their role can help you appreciate Flutter's build process and performance optimizations.

**Comment by gjwgit** [comment]
> `rattlengxxx` folder is internally used by flutter in the build process. I believe those folders will not be generated in the production version.
> 
> >

Thanks for that insight @Lutra-Fs. I can confirm the rattleng folder is **not** created for a `--release` compile.
