### ISSUE TITLE
EXPLORE: Filter Numeric Options in Dropdown Menus on Tests Page

### ISSUE THREAD

**Issue by junhaow1** [gjwgit/rattle#382]
## Description
Enhance the user experience on the Tests page of our rattleNG app by implementing a filter for the "input" and "second" DropdownMenus. Currently, these dropdowns display a mix of numeric and non-numeric options, which can confuse users and make selection more cumbersome. This improvement will introduce a filter to ensure that only numeric options are displayed, streamlining the selection process and aligning with user expectations for numeric input fields.

## Why
Displaying only numeric options in the dropdown menus will improve the usability and clarity of the Tests page. It reduces the likelihood of user errors and enhances the overall efficiency of navigating through numeric fields. By filtering out non-numeric options, we cater directly to the intended functionality of these dropdowns, thereby improving the interface’s intuitiveness and preventing potential misentries that could affect the app’s performance and user satisfaction.

## Closing Criteria

- [x]  A filter is implemented to ensure that only numeric options are displayed in the "input" and "second" DropdownMenus on the Tests page.

 - [x] The dropdown menus are tested to confirm that no non-numeric options are present.
 - [x] The user interface is reviewed to ensure the filter enhances usability without causing disruptions or errors.

**Comment by gjwgit** [comment]
This is done in the VISUAL feature so can do the same?

**Comment by gjwgit** [comment]
Use the data from the `meta` provide for the required information. If any information is missing then create an issue to update the meta provider.

**Comment by junhaow1** [comment]
![image](https://github.com/user-attachments/assets/9809fe0b-f000-40d1-b40d-31509202696a)
![image](https://github.com/user-attachments/assets/1c8213c1-2ec2-4b56-a814-43cea95690d0)

**Comment by junhaow1** [comment]
https://github.com/gjwgit/rattleng/pull/571 PR created
