### ISSUE TITLE
IMAGE: Images are too large by default.

### ISSUE THREAD

**Issue by gjwgit** [gjwgit/rattle#385]
The scaling of images to fill the space is great but the default seems too large:

![Image](https://github.com/user-attachments/assets/cc604747-821d-47ef-840d-32a2afa490c9)

Notice the bottom of the image is truncated.

This remains the case even when the window is maximised.

**Comment by Lutra-Fs** [comment]
@zheyxu are you working on this issue? Can I take this one? I will fix it at this weekend.

**Comment by Lutra-Fs** [comment]
> The scaling of images to fill the space is great but the default seems too large:
> 
> ![Image](https://private-user-images.githubusercontent.com/1681429/364979028-cc604747-821d-47ef-840d-32a2afa490c9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgxMjYyNDksIm5iZiI6MTcyODEyNTk0OSwicGF0aCI6Ii8xNjgxNDI5LzM2NDk3OTAyOC1jYzYwNDc0Ny04MjFkLTQ3ZWYtODQwZC0zMmEyYWZhNDkwYzkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAwNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMDVUMTA1OTA5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YjAxMjA2MmY2YmU4YWZiYWY5NjU0MWJhYzk3NWU0ZTljYzZiMWUxYjNhYzdjMTE2OGNhZDJlMjIyNGM2NjNmYiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.O5Iz8p4HXki8B62Xx-Z3UGpdTmkAJWAzSpQiC9P_j9c)
> 
> Notice the bottom of the image is truncated.
> 
> This remains the case even when the window is maximised.

Given that the image is already wrapped in an `InteractiveViewer` and can be zoomed in/out via mouse scroll and moved via drag, the solution is to adjust the default fit option. Specifically, we should update the `SvgPicture.memory` widget to use `BoxFit.scaleDown` instead of `BoxFit.contain`. And I believe no further actions are required.

**Comment by zheyxu** [comment]
![Image](https://github.com/user-attachments/assets/a6aae8a7-ebef-43da-b301-909607d2156c)

**Comment by zheyxu** [comment]
Made pr https://github.com/gjwgit/rattleng/pull/543
