### ISSUE TITLE
MODELS: Add `Target:` for information

### ISSUE THREAD

**Issue by gjwgit** [gjwgit/rattle#389]
For information purposes add `Target: rain_tomorrow` just after the `Model Builder: rpart` information text.

![Image](https://github.com/user-attachments/assets/79c8da73-0eab-4cff-8950-81a9f6f78f36)

**Comment by gjwgit** [comment]
Note that Model Builder is no longer present. Place the Target after the Include missing.

**Comment by junhaow1** [comment]
![Image](https://github.com/user-attachments/assets/a51d6bf3-427a-49cb-b3ad-f1ddc111a5df)

**Comment by junhaow1** [comment]
![Image](https://github.com/user-attachments/assets/d6599edf-249d-4ade-86e1-09f42d3bc17a)
![Image](https://github.com/user-attachments/assets/34289745-2c0c-413d-a476-a51d0ef04300)

**Comment by junhaow1** [comment]
https://github.com/gjwgit/rattleng/pull/548 PR created

**Comment by gjwgit** [comment]
Looks great. Can we please do so for the rest as well:

- [x] Association
- [x] Linear
- [x] Neural
- [x] Forest
- [x] Boost
- [x] SVM

**Comment by junhaow1** [comment]
https://github.com/gjwgit/rattleng/pull/554 PR created
