### ISSUE TITLE
CLEANUP: When a variable is selected set VARIABLE option

### ISSUE THREAD

**Issue by gjwgit** [gjwgit/rattle#391]
## Description

For the TRANSFORM tab CLEANUP feature if a user chooses a variable the default option should go to VARIABLE.

**Or else, the Variable selection is not available until the VARIABLE option is chosen.**

**Comment by junhaow1** [comment]
demo video: 
https://github.com/user-attachments/assets/4ee1aa46-34c7-4ad3-ae27-228818ed380a

**Comment by junhaow1** [comment]
I couldn't find a good way to make the variableChooser blank or empty if the ChoiceChipTip 'Variable' is not selected, so I chose this implementation.

**Comment by gjwgit** [comment]
Thanks @junhaow1. Can the text inside the box be made grey when we can not select?

**Comment by junhaow1** [comment]
> Thanks @junhaow1. Can the text inside the box be made grey when we can not select?

On it

**Comment by junhaow1** [comment]
![Image](https://github.com/user-attachments/assets/afc3e7e1-d5cf-4221-96d0-c96d67da87ef)
![Image](https://github.com/user-attachments/assets/cc20b252-5ed4-4c0b-8765-b98c4cd39607)


![Image](https://github.com/user-attachments/assets/41fbc783-a59f-4ad9-b160-088a7788ea14)

**Comment by junhaow1** [comment]
![Image](https://github.com/user-attachments/assets/5057cd07-4e30-41a0-b3c1-fbf3457d6bf0)

**Comment by junhaow1** [comment]
https://github.com/gjwgit/rattleng/pull/460 PR created
