### ISSUE TITLE
ROLES: Add Unique and Missing colums between Role and Content

### ISSUE THREAD

**Issue by gjwgit** [gjwgit/rattle#392]
## Description

Add two new columns between the ROLE and CONTENT columns to list the UNIQUE and MISSING counts.

Also move the Type column to after the Role column and before UNIQUE column.

## Why

So that a data scientist has the information required in order to decide on the variable role.

![Image](https://github.com/user-attachments/assets/f40848a1-8b49-492d-900d-8435cc4ad2bc)

**Comment by gjwgit** [comment]
On hold until #315 as a dependency.

**Comment by gjwgit** [comment]
The branch gjw/315 is developing a JSON data model for the loaded R dataset which we should be able to utilise to get the information we need. It is going into the metaData provide:

![Image](https://github.com/user-attachments/assets/6f4c46c4-11d7-48bf-b7eb-f3e9f5b315ee)

**Comment by gjwgit** [comment]
This is ready to proceed. Let me know any meta data you need that is missing.

**Comment by junhaow1** [comment]
demo dataset: 
<img width="1201" alt="image" src="https://github.com/user-attachments/assets/a44830bd-24d7-4784-8165-92785a018dc1">


large dataset: 
<img width="1219" alt="image" src="https://github.com/user-attachments/assets/cf9687dc-bef2-41a2-9965-4e1df0bcf73f">

**Comment by junhaow1** [comment]
https://github.com/gjwgit/rattleng/pull/522 PR created 

- [x] make prep
