### ISSUE TITLE
DATASET: Set variables as IGNORE as the levels are more than 10 levels.

### ISSUE THREAD

**Issue by zheyxu** [gjwgit/rattle#404]
If they are categorised.

**Comment by gjwgit** [comment]
If the variable is a factor or character with more than 20 levels then IGNORE by default.

**Comment by zheyxu** [comment]
Made pr https://github.com/gjwgit/rattleng/pull/427

**Comment by zheyxu** [comment]
![Image](https://github.com/user-attachments/assets/be0cdbdb-4d3d-4974-a1d9-fe691c866f0f)
Ignore variables more than 10 levels by default.

**Comment by gjwgit** [comment]
Use MAXFACTOR instead of 10 or 20. Currently Rattle use MAXFACTOR=20 but the intention is that the user can change this in SETTINGS.
