### ISSUE TITLE
OVERVIEW: Redesign the overview page layouts

### ISSUE THREAD

**Issue by gjwgit** [gjwgit/rattle#411]
## Description

As Bob Muenchen points out the overview pages can be quite wide and thus more difficult to read. Consider a two column approach. For example for the Welcome page, the left has a max of perahps 100 chars and the right has the list of Resources.

## Why

So that users can more comfortably read the text.

**Comment by junhaow1** [comment]
![Image](https://github.com/user-attachments/assets/5b5a02fb-b5cf-4254-a291-15c1d9254ff6)

**Comment by junhaow1** [comment]
Before: 

![Image](https://github.com/user-attachments/assets/33205e28-c726-4113-9923-cc0fcc82ff8d)

After: 

![Image](https://github.com/user-attachments/assets/3ecb5798-7922-4f54-95fe-a1cd9ec1e70c)

**Comment by junhaow1** [comment]
https://github.com/gjwgit/rattleng/pull/503 PR created
