### ISSUE TITLE
PAGE: Activate the dots to go to the corresponding page

### ISSUE THREAD

**Issue by gjwgit** [gjwgit/rattle#412]

**Comment by junhaow1** [comment]
demo video: 
https://github.com/user-attachments/assets/d9a92ce5-f641-46a2-bfee-7940bb49450d

**Comment by junhaow1** [comment]
Some Tests to fix 

![Image](https://github.com/user-attachments/assets/3d22e380-5dce-4d51-a42d-b8630280998d)

**Comment by junhaow1** [comment]
https://github.com/gjwgit/rattleng/pull/431 PR created 

Only 3 tests are failing, which also fail on my dev branch. It seems like a machine issue; I will investigate this in another ticket. For this ticket, the testing has passed.
![Image](https://github.com/user-attachments/assets/05695c62-aa0d-4bfc-b429-f895ac96396c)
