### ISSUE TITLE
DATASET ROLES: The headings need to be left aligned

### ISSUE THREAD

**Issue by gjwgit** [gjwgit/rattle#416]
## Description

The headings need to be left aligned wit the below columns. So here VARIABLE is fine but TYPE looks to be right aligned, ROLE sticks out to the left and CONTENT looks like it is centre aligned. They need to all be left aligned.

![Image](https://github.com/user-attachments/assets/a24aba9d-abfb-48c9-9035-7dc22bc066b9)

If I resize my window (narrower) the labels are aligned properly?

![Image](https://github.com/user-attachments/assets/bf210de6-3532-443d-80a7-cc4171bcf364)

## Why

So that the presentation looks right - the user is not unnecessarily wondering why some headings are left aligned and others are close but not really.

**Comment by junhaow1** [comment]
https://github.com/gjwgit/rattleng/pull/432 PR created

**Comment by junhaow1** [comment]
<img width="2136" alt="image" src="https://github.com/user-attachments/assets/c3f0f2ff-d1c7-4300-bdb7-6dd18989e285">
