### ISSUE TITLE
BUG: page and page indicator  freezes

### ISSUE THREAD

**Issue by yixiangyin** [gjwgit/rattle#423]
load demo -> explore -> summary -> click the right arrow button -> build -> you can't change pages now

![Image](https://github.com/user-attachments/assets/7dcd8bbe-d571-4c35-8b0b-b3cc3045b9ff)

**Comment by gjwgit** [comment]
Duplicated with #425

**Comment by gjwgit** [comment]
Working okay now. Closing.
