### ISSUE TITLE
DATASET: Update the weather dataset to 2024

### ISSUE THREAD

**Issue by gjwgit** [gjwgit/rattle#428]
## Description

Load the demo dataset from the assets and ensure it is the latest.

But, loading from assets into R directly is not feasible.

Load the asset and save into /tmp then load from there into R.

This will require almost every `demo` test to be updated.

**Comment by gjwgit** [comment]
Assign to @junhaow1 to update all tests.

**Comment by junhaow1** [comment]
add comments: expect the text under rain row

**Comment by gjwgit** [comment]
FYI my current testing:

```
18 Sep 12:18:07 gjw@kadesh ~gjwgit/rattleng$ make qtest.tmp
make qtest > qtest.tmp
integration_test/app_test.dart YES
integration_test/dataset_demo_test.dart NO *****
integration_test/dataset_large_test.dart YES
integration_test/dataset_reset_test.dart NO *****
integration_test/dataset_reset_visual_test.dart YES
integration_test/explore_correlation_demo_test.dart NO *****
integration_test/explore_correlation_large_test.dart YES
integration_test/explore_demo_test.dart NO *****
integration_test/explore_large_test.dart YES
integration_test/explore_missing_demo_test.dart NO *****
integration_test/explore_missing_large_test.dart YES
integration_test/explore_set_ignore_test.dart YES
integration_test/explore_visual_demo_test.dart YES
integration_test/explore_visual_large_test.dart YES
integration_test/model_cluster_demo_test.dart YES
integration_test/model_nnet_demo_test.dart NO *****
integration_test/model_nnet_large_test.dart NO *****
integration_test/model_tree_demo_test.dart NO *****
integration_test/model_tree_large_test.dart YES
integration_test/transform_cleanup_ignore_demo_test.dart NO *****
integration_test/transform_impute_demo_test.dart NO *****
integration_test/transform_impute_large_test.dart YES
```

**Comment by junhaow1** [comment]
- [x] integration_test/dataset_demo_test.dart NO *****

- [x] integration_test/dataset_reset_test.dart NO *****
- [x] integration_test/explore_correlation_demo_test.dart NO *****
- [x] integration_test/explore_demo_test.dart NO *****
- [x] integration_test/explore_missing_demo_test.dart NO *****

- [ ] integration_test/model_nnet_demo_test.dart NO *****
- [ ] integration_test/model_nnet_large_test.dart NO *****
- [ ] integration_test/model_tree_demo_test.dart NO *****

- [ ] integration_test/transform_cleanup_ignore_demo_test.dart NO *****
- [ ] integration_test/transform_impute_demo_test.dart NO *****

**Comment by junhaow1** [comment]
make transform_impute_demo.qtest     
fails ![Image](https://github.com/user-attachments/assets/2e4bab6e-849d-406c-933c-619268394cc4)
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following FileSystemException was thrown running a test:
Cannot open file, path = '/weather.csv' (OS Error: Read-only file system, errno = 30)

When the exception was thrown, this was the stack:
#0      _checkForErrorResponse (dart:io/common.dart:55:9)
#1      _File.open.<anonymous closure> (dart:io/file_impl.dart:381:7)
<asynchronous suspension>
#7      _File.writeAsBytes.<anonymous closure> (dart:io/file_impl.dart:634:34)
<asynchronous suspension>
#8      copyAssetToTempDir (package:rattle/utils/copy_asset_to_tempdir.dart:56:3)
<asynchronous suspension>
#9      DatasetPopup.build.<anonymous closure> (package:rattle/features/dataset/popup.dart:147:23)
<asynchronous suspension>
(elided 5 frames from dart:async and package:stack_trace)

**Comment by junhaow1** [comment]
Hi @gjwgit  , https://github.com/gjwgit/rattleng/commit/ebf2a034febdb3c552c41859a12bda2cc1d0721b 
Could you please help me confirm if this is the correct logic? I am not 100% sure of the "Cleanup" feature, i think it is good to have a second reviewer on this.

**Comment by gjwgit** [comment]
All tests updated and all tests are now passing. Once @junhaow1 and @zheyxu confirms the tests pass then can merge PR

**Comment by gjwgit** [comment]
![Image](https://github.com/user-attachments/assets/612ebfcc-3e6b-4f11-9a79-b2981ba9c298)

**Comment by gjwgit** [comment]
Merged.
