### ISSUE TITLE
NEURAL: Add neuralnet() as an option

### ISSUE THREAD

**Issue by gjwgit** [gjwgit/rattle#465]
Kerry would like multi-layer for the data mining course.

The neuralnet package seems to be the one.

Add ChoiceChip for nnet and neuralnet.

+ https://datascienceplus.com/fitting-neural-network-in-r/
+ https://www.r-bloggers.com/2010/12/r-code-example-for-neural-networks/

**Comment by zheyxu** [comment]
![Image](https://github.com/user-attachments/assets/b1bc0003-68bf-4c9b-aa2c-9643ed1445e5)
Made pr https://github.com/gjwgit/rattleng/pull/525
