### ISSUE TITLE
NEURAL: Add another checkbox to config to 'Ignore Categoric'

### ISSUE THREAD

**Issue by gjwgit** [gjwgit/rattle#468]
When this is checked then when building the model ignore the categoric variables.

- [x] Update R code to remove categoric from dataset passed to nnet()
- [x] Add new test `model_nnet_demo_numeric_test.dart`

**Comment by zheyxu** [comment]
For `nnet()`,
![Image](https://github.com/user-attachments/assets/d189c2b8-0d68-4fa2-a51e-5af77cf0e498)

**Comment by zheyxu** [comment]
For `neuralnet`
![Image](https://github.com/user-attachments/assets/c631fba9-de23-4833-a779-90820d068148)

**Comment by zheyxu** [comment]
Made pr https://github.com/gjwgit/rattleng/pull/544
