### ISSUE TITLE
TREE: Add tooltips for CONDITIONAL and TRADITIONAL

### ISSUE THREAD

**Issue by gjwgit** [gjwgit/rattle#471]
![Image](https://github.com/user-attachments/assets/86f28104-d657-42fc-a073-ea95bd085e96)

**Comment by zheyxu** [comment]
![Image](https://github.com/user-attachments/assets/26588785-ee7b-42d9-b665-ec49a32154f5)
![Image](https://github.com/user-attachments/assets/cd0f9841-adb5-48c2-9ece-898422b68efe)
Made pr https://github.com/gjwgit/rattleng/pull/489
