### ISSUE TITLE
CLUSTER: Implement EWKM

### ISSUE THREAD

**Issue by gjwgit** [gjwgit/rattle#477]

**Comment by zheyxu** [comment]
Current updates:
![Image](https://github.com/user-attachments/assets/54270dd9-aee7-44bb-9c77-8c49e7cc50ad)
![Image](https://github.com/user-attachments/assets/9029a1b1-ae3b-4e4f-892f-d6e6ffd7050e)

**Comment by zheyxu** [comment]
Made pr https://github.com/gjwgit/rattleng/pull/506
