### ISSUE TITLE
CLUSTER: Implement HIERARCHICAL

### ISSUE THREAD

**Issue by gjwgit** [gjwgit/rattle#478]

**Comment by zheyxu** [comment]
![Image](https://github.com/user-attachments/assets/62db6c7a-546c-4fe1-984e-037cbd232cdb)

**Comment by zheyxu** [comment]
Made pr https://github.com/gjwgit/rattleng/pull/529

**Comment by gjwgit** [comment]
- [ ] Perhaps move the Re-Scale checkbox to the top Row. That seems to be how we did it in other configs.

![Image](https://github.com/user-attachments/assets/40c1284c-8377-4bb4-b3e9-5dc79eb521b0)

**Comment by zheyxu** [comment]
<img width="1487" alt="Screenshot 2024-10-17 at 10 05 01 am" src="https://github.com/user-attachments/assets/425bfb8e-03bc-4bb2-a92d-a41057ac017d">
