### ISSUE TITLE
TESTING: Fix broken integration tests for updated PAGE_VIEW

### ISSUE THREAD

**Issue by junhaow1** [gjwgit/rattle#485]
## Description
This issue involves fixing the integration tests that were broken after changes were made in the dataset build process and the Roles page. Due to the complexity and the number of tests affected, testing and debugging the issue locally has proven time-consuming. To expedite the process and improve efficiency, remote testing via RDP (Remote Desktop Protocol) will be set up and utilized for this task. This will ensure a faster workflow for test repair and validation.

## Why
The current broken integration tests impact the stability of the platform and need to be resolved promptly. By enabling RDP access, it allows for more efficient testing, quicker debugging, and the ability to verify fixes in a controlled environment. This step is crucial for maintaining the integrity of the build and for ensuring that changes to the Roles page are properly tested before moving forward.

## Closing Criteria
 

- [x] Remote access via RDP is set up and functional for test environment access.

- [x] All broken integration tests related to the Roles page and dataset build are identified and fixed.

**Comment by Lutra-Fs** [comment]
I’m curious to know what your main goal is with this post.

I was thinking, why don’t we just use RDP or VAC to connect to a PC and run the test there?

**Comment by gjwgit** [comment]
That's the intent - RDP is a little misleading here and nbothing to do with Rattle per se - it is just that we might have access to a remote server to do the testing on, through RDP or VNC or X2Go etc. It makes it easier then for the long tests to be run without constantly stealing focus on your desktop!

**Comment by gjwgit** [comment]
I've removed the RDP reference from title. This issue is focused on getting the tests working for the new page navigation.

**Comment by gjwgit** [comment]
Suggestion: `verifyNextPage()` should become `verifyPage()`. Then `gotoNextPage()` should be in the main test script. That way the main test script does more of the controlling of where we go and when we test and it works better for the updated Pages View.

**Comment by junhaow1** [comment]
Failed tests TODO list 
- [x]  demo_explore_visual
- [ ]  demo_model_nnet
- [ ]  demo_model_tree
- [x]  large_dataset
- [x]  large_explore_correlation
- [x]  large_explore_missing
- [x]  large_explore
- [x]  large_explore_visual
- [ ]  large_model_nnet
- [ ]  large_model_tree
- [x]  reset_dataset
- [ ]  sherlock_dataset

**Comment by junhaow1** [comment]
working branch : https://github.com/gjwgit/rattleng/tree/kev/485_test

**Comment by junhaow1** [comment]
(base) kev@Junhaos-MacBook-Pro rattleng % make qtest.tmp
make qtest > qtest.tmp
integration_test/app_test.dart YES
integration_test/demo_dataset_ignore_test.dart YES
integration_test/demo_dataset_test.dart YES
integration_test/demo_explore_correlation_test.dart NO *****
integration_test/demo_explore_missing_test.dart NO *****
integration_test/demo_explore_test.dart NO *****
integration_test/demo_explore_visual_test.dart NO *****
integration_test/demo_model_cluster_test.dart YES
integration_test/demo_model_nnet_test.dart NO *****
integration_test/demo_model_tree_test.dart YES
integration_test/demo_transform_cleanup_ignore_test.dart NO *****
integration_test/demo_transform_impute_test.dart YES
integration_test/large_dataset_ignore_test.dart YES
integration_test/large_dataset_test.dart YES
integration_test/large_explore_correlation_test.dart NO *****
integration_test/large_explore_missing_test.dart NO *****
integration_test/large_explore_test.dart YES
integration_test/large_explore_visual_test.dart NO *****
integration_test/large_model_nnet_test.dart NO *****
integration_test/large_model_tree_test.dart NO *****
integration_test/large_transform_impute_test.dart YES
integration_test/reset_dataset_test.dart YES
integration_test/reset_dataset_visual_test.dart YES
integration_test/sherlock_dataset_test.dart NO *****

**Comment by junhaow1** [comment]
- [x] integration_test/demo_explore_correlation_test.dart *****

- [x] integration_test/demo_explore_missing_test.dart
- [x] integration_test/demo_explore_test.dart NO *****
- [x] integration_test/demo_explore_visual_test.dart NO *****
- [x] integration_test/demo_model_nnet_test.dart NO *****
- [x] integration_test/demo_transform_cleanup_ignore_test.dart NO *****
- [x] integration_test/large_explore_correlation_test.dart NO *****
- [ ] integration_test/large_explore_missing_test.dart NO *****
- [x] integration_test/large_explore_visual_test.dart NO *****
- [ ] integration_test/large_model_nnet_test.dart NO *****
- [x] integration_test/large_model_tree_test.dart NO *****
- [x] integration_test/sherlock_dataset_test.dart NO *****

**Comment by gjwgit** [comment]
Confirm. All DEMO tests now working for me

```
03 Oct 10:13:06 gjw@kadesh ~gjwgit/rattleng$ make qtest.all
make qtest > qtest.all
integration_test/app_test.dart YES
integration_test/demo_dataset_ignore_test.dart YES
integration_test/demo_dataset_test.dart YES
integration_test/demo_explore_correlation_test.dart YES
integration_test/demo_explore_missing_test.dart YES
integration_test/demo_explore_test.dart YES
integration_test/demo_explore_visual_test.dart YES
integration_test/demo_model_cluster_test.dart YES
integration_test/demo_model_nnet_test.dart YES
integration_test/demo_model_tree_test.dart YES
integration_test/demo_transform_cleanup_ignore_test.dart YES
integration_test/demo_transform_impute_test.dart YES
```

**Comment by junhaow1** [comment]
<img width="888" alt="image" src="https://github.com/user-attachments/assets/a7f71759-46b9-42ff-bdd1-d6a7c03ef758">
