### ISSUE TITLE
NAVIGATION: Remain on current page after a BUILD except if on page 0

### ISSUE THREAD

**Issue by gjwgit** [gjwgit/rattle#490]
## Description

For example

DEMO > SUMMARY > BUILD > NAVIGATE to GLIMPSE > BUILD It should stay on the GLIMPSE page.

We want the following behaviour on EVERY PAGES:

The general rule will be if on page 0 then after a BUILD try going to page 1. 

If BUILD is pressed on any page other than page 0 then do not navigate.

**Comment by junhaow1** [comment]
demo: 
https://github.com/user-attachments/assets/f32c86bb-e426-4a3c-b1e8-1083e2d52d60

**Comment by gjwgit** [comment]
Well and good for a single feature. But this is poorly implemented anyhow (DRY) and needs to be implemented for **ALL** features.

**Comment by junhaow1** [comment]
Example usage : 
![Image](https://github.com/user-attachments/assets/4c754249-a9d4-4b93-95cb-c8d4ea5f0da1)

![Image](https://github.com/user-attachments/assets/632bc445-9fd0-48c7-ac99-9470c66ec24a)

Applied the change to all features now

**Comment by junhaow1** [comment]
working branch : https://github.com/gjwgit/rattleng/tree/kev/490_remain

waiting for change some tests

**Comment by junhaow1** [comment]
TODO list , failed tests 
- [x] integration_test/demo_explore_correlation_test.dart NO *****
- [x] integration_test/demo_model_nnet_test.dart NO *****
- [ ] integration_test/large_dataset_ignore_test.dart NO *****
- [x] integration_test/large_explore_test.dart NO *****
- [ ] integration_test/large_explore_visual_test.dart NO *****
- [ ] integration_test/large_model_nnet_test.dart NO *****
- [ ] integration_test/large_model_tree_test.dart NO *****

**Comment by junhaow1** [comment]
latest example usage: 
![Image](https://github.com/user-attachments/assets/c3f605c5-2c00-42fb-9d14-bf70504f6683)

**Comment by junhaow1** [comment]
https://github.com/gjwgit/rattleng/pull/496 PR created

**Comment by junhaow1** [comment]
<img width="627" alt="image" src="https://github.com/user-attachments/assets/e4b2b2ee-2246-4189-8f62-4cdc616be67e">
