### ISSUE TITLE
TRANSFORM: Update config to use utils/variable_chooser rather than local version

### ISSUE THREAD

**Issue by gjwgit** [gjwgit/rattle#501]
## Description

Perhaps for histroric reason, 

- [x] 'recode/config.dart`
- [x] `impute/config.dart`

define their own `variableChooser`. 

Migrate to using `utils/variable_chooser.dart`

## Why

So that we reduce the amount of repeated code, reducing technical debt, and improving maintainability.

**Comment by junhaow1** [comment]
https://github.com/gjwgit/rattleng/pull/505 PR created
