### ISSUE TITLE
RECODE: Review and fix current failure

### ISSUE THREAD

**Issue by gjwgit** [gjwgit/rattle#507]
## Description

I am currently seeing problems with the RECODE feature not working

DEMO -> TRANSFORM -> RECODE -> BUILD (default min_temp and Quantiles of 4).

The Summary displayed is not updated with the new variable. The CONSOLE shows the new variable in the summary. Going back to TRANSFORM -> RECODE and the Summary now includes the new variable. However the console says:

```
flutter: R SOURCE                 dataset_template.R
flutter: ERROR: unidentified variables: BQT_min_temp_4!
```

![Image](https://github.com/user-attachments/assets/ca459dd1-73a7-44c1-a212-b17a276e126d)

**Comment by junhaow1** [comment]
![Image](https://github.com/user-attachments/assets/44c38471-fe27-442d-ba3c-e927e390ed5f)

![Image](https://github.com/user-attachments/assets/9a33b1bd-b5d4-4692-bfe2-62e55319035d)

![Image](https://github.com/user-attachments/assets/288445ca-3cda-4349-88da-376a0f1d7905)

**Comment by junhaow1** [comment]
Unidentified variable: BQT_min_temp_4. This bug has been fixed, but sometimes the summary display does not update with the new variable. This is the only issue to investigate and resolve.

**Comment by junhaow1** [comment]
Demo video: 
https://github.com/user-attachments/assets/5611b0bf-7bdc-459a-bdb5-820ba3ccf003

**Comment by junhaow1** [comment]
PR created https://github.com/gjwgit/rattleng/pull/580
