### ISSUE TITLE
RESCALE: Add tooltips to each of the chips.

### ISSUE THREAD

**Issue by gjwgit** [gjwgit/rattle#511]

**Comment by junhaow1** [comment]
<img width="392" alt="image" src="https://github.com/user-attachments/assets/66d871c9-a23b-4297-a234-332d3219f6f3">
<img width="363" alt="image" src="https://github.com/user-attachments/assets/6709f0b1-d2e3-4121-9f6c-ad2c2db57c97">
<img width="379" alt="image" src="https://github.com/user-attachments/assets/38d7045f-3620-4882-8382-4ea2b17afb25">
<img width="380" alt="image" src="https://github.com/user-attachments/assets/b21ff3b1-981c-4492-ab86-daec5314edfc">
<img width="362" alt="image" src="https://github.com/user-attachments/assets/2d8ca2bc-138c-44a7-83e8-3cbc3e6b7259">
<img width="353" alt="image" src="https://github.com/user-attachments/assets/8f92bff7-0e99-4bfa-8196-7f89b52b72ad">
<img width="348" alt="image" src="https://github.com/user-attachments/assets/e09b7903-972b-4db1-a295-a541ec318ad6">

**Comment by junhaow1** [comment]
PR created https://github.com/gjwgit/rattleng/pull/528
