### ISSUE TITLE
RESCALE: Interval number field is available only when Interval chip is selected

### ISSUE THREAD

**Issue by gjwgit** [gjwgit/rattle#512]
## Description 

The Interval number field is only relevant when the Interval chip is selected. It should be greyed out and not eactive unless the Interval chip is chosen.

![Image](https://github.com/user-attachments/assets/c0ed480b-e230-4226-a1c5-f9b807cdb839)

**Comment by gjwgit** [comment]
It should operate like Variable in CLEANUP

**Comment by junhaow1** [comment]
<img width="984" alt="image" src="https://github.com/user-attachments/assets/51044219-58d7-4cb3-aad2-4f2fa695eb6f">

<img width="412" alt="image" src="https://github.com/user-attachments/assets/1ab4e641-7418-4d90-90a9-4808367ee39d">

**Comment by junhaow1** [comment]
https://github.com/gjwgit/rattleng/pull/524 PR created
