### ISSUE TITLE
TEXT PAGE: Add a button for each text page to generate a PDF from the contents and pop it up.

### ISSUE THREAD

**Issue by gjwgit** [gjwgit/rattle#513]
## Description

For a TextPage, similar to the ImagePage, it will be useful to have a button to view the text of the page in an external viewer as PDF, and to save the text as PDF into a file.

## Why

So that a user is able to more easily compare a result with another model result. For example, I want to build kmeans and then ewkm. How to best compare them? After building the second model we can't currently restore the first easily. But viewing it externally allows this comparison easily.

**Comment by junhaow1** [comment]
<img width="1514" alt="image" src="https://github.com/user-attachments/assets/4420ce47-7aa1-4544-83d1-5beea0bd79fe">

**Comment by junhaow1** [comment]
working branch https://github.com/gjwgit/rattleng/tree/kev/513_button

**Comment by gjwgit** [comment]
Use the same style for the button as we use in the image_page widget.

![Image](https://github.com/user-attachments/assets/3dad66be-fd6b-476e-9833-de3408a821be)

**Comment by junhaow1** [comment]
some format issue
![Image](https://github.com/user-attachments/assets/9af7a4d8-1cd5-4c14-af65-c6855f06518e)
![Image](https://github.com/user-attachments/assets/b347d5e9-9365-4b6e-b1ea-03c11d22c8b4)

**Comment by junhaow1** [comment]
https://github.com/gjwgit/rattleng/pull/537 PR created
