### ISSUE TITLE
IMPUTE: Constant text field only accessible when CONSTANT enabled

### ISSUE THREAD

**Issue by gjwgit** [gjwgit/rattle#515]
## Description

- [x] The Constant text field should be enabled only when the CONSTANT chip is active. 
- [x] If variable is numeric then the default value (if not already set) should be 0
- [x] If the variable is categoric then the default value (if not already set) should be 'Missing'
- [x] The Constant can not be character for a numeric variable.
- [x] For a categoric variable it is okay to be numeric - the R code uses "0"
- [x] Remove the Zero/Missing chip - it is redundant
- [x] Add tooltips for the chips and the TextField
- [x] Add gap between the Constant chip and the other chips
- [x] Remove the large gap (small gap only) between Constant chip and Constant TextField

## Why

So that we remove redundancy, explain each operation, and layout the options to better support the user.

**Comment by junhaow1** [comment]
demo video: 

https://github.com/user-attachments/assets/a16f246a-027d-4326-9fe0-4b74c892f57e

**Comment by junhaow1** [comment]
https://github.com/gjwgit/rattleng/pull/523 PR created

**Comment by gjwgit** [comment]
Changes requested to the PR.

**Comment by junhaow1** [comment]
> Changes requested to the PR.

https://github.com/gjwgit/rattleng/pull/523/files changed as requested

**Comment by junhaow1** [comment]
<img width="1044" alt="image" src="https://github.com/user-attachments/assets/46ef950a-a2d7-466c-8395-138127eb9a10">

**Comment by junhaow1** [comment]
new demo video: 
@gjwgit 

https://github.com/user-attachments/assets/72ec1074-3255-43a1-a9cf-fc690f2d0c8f
