### ISSUE TITLE
DATASET: Move the View Dataset button into the Dataset ROLES tab

### ISSUE THREAD

**Issue by gjwgit** [gjwgit/rattle#517]
## Description

Move the View Dataset button into the ROLES page. 

## Why

So that there is a view dataset button where users expect to be reviewing the dataset as in on the ROLES page. Suggested by Bob Muenchen.

**Comment by junhaow1** [comment]
![Image](https://github.com/user-attachments/assets/94666d36-0cdf-4e0e-8abd-1be819b7bce3)
The View button on top right?

**Comment by junhaow1** [comment]
![Image](https://github.com/user-attachments/assets/d34dbce2-fb4c-4039-a11c-8477ab3fc89b)

**Comment by junhaow1** [comment]
https://github.com/gjwgit/rattleng/pull/569 PR created

**Comment by gjwgit** [comment]
Let's retain this version with the VIEW button on the right and add a ROW along the top as the CONGIF panel for this page - see the required functionality in #374 where we want to add two buttons - INPUT and IGNORE.
