### ISSUE TITLE
ROLES: Change spacing between columns

### ISSUE THREAD

**Issue by gjwgit** [gjwgit/rattle#527]
## Description

Could we please have more space between Variable and Role and less space between Role and Type.

![Image](https://github.com/user-attachments/assets/7f8f8b91-ab42-46c9-8f76-c1a725ffebc0)

**Comment by junhaow1** [comment]
demo video: 
https://github.com/user-attachments/assets/7dce1647-c538-4f03-9fa5-515717e5eba8

**Comment by junhaow1** [comment]
Working branch 
https://github.com/gjwgit/rattleng/tree/kev/527_spacing

**Comment by junhaow1** [comment]
https://github.com/gjwgit/rattleng/pull/533 PR created
