### ISSUE TITLE
CLUSTER: Add visualisation (eg. ggdendro)

### ISSUE THREAD

**Issue by zheyxu** [gjwgit/rattle#530]
- [x] KMeans
- [x] Ewkm
- [x] Hierarchical
- [ ] bicluster

**Comment by gjwgit** [comment]
Example for hclust:

```
library(ggdendro)


library(ggplot2)
hc <- hclust(dist(USArrests), "ave")

# Demonstrate plotting directly from object class hclust
p <- ggdendrogram(hc, rotate = FALSE)
print(p)
ggdendrogram(hc, rotate = TRUE)

# demonstrate converting hclust to dendro using dendro_data first
hcdata <- dendro_data(hc)
ggdendrogram(hcdata, rotate = TRUE, size = 2) +
  labs(title = "Dendrogram in ggplot2")
```

**Comment by zheyxu** [comment]
Implemented work:
![Image](https://github.com/user-attachments/assets/ba06ee25-68a3-4c36-aa29-d1d3ce053916)
![Image](https://github.com/user-attachments/assets/7c3fee79-24f3-49a3-8d01-e6db2567897e)
![Image](https://github.com/user-attachments/assets/3ca85f01-74a4-428b-a706-1b2e7718f378)

**Comment by zheyxu** [comment]
Data plot has not been implemented yet after hours of try:

![Image](https://github.com/user-attachments/assets/d5671ef6-17ec-44d7-81ec-5d485687249b)

**Comment by zheyxu** [comment]
https://github.com/gjwgit/rattleng/pull/541 for the current work.
