### ISSUE TITLE
DATASET: Check that user supplied path exists before dispatch to R

### ISSUE THREAD

**Issue by gjwgit** [gjwgit/rattle#536]
## Description

The path to a filename that a user has typed in needs to be checked to make sure it exist before we attempt to ask R to load the file.

Here I have typed a path:

![Image](https://github.com/user-attachments/assets/56c70f70-8c58-4db0-b0f0-88f4ce75207a)

But the path does not exist. There should be a popup to say the path does not exist rather than simply attempting to load the file in R and silently failing.

![Image](https://github.com/user-attachments/assets/45ff74dd-f0a4-40ae-b700-2c76cebc0311)

**Comment by gjwgit** [comment]
This task requires refactoring the handling of CSV and TXT file loading. Currently there are several pathways and two scenarios (first load and loading when there is already a dataset loaded). Needs to be cleaned up and remove repeated coding.

**Comment by junhaow1** [comment]
The popup was implemented by Graham three weeks ago. I am currently working on refactoring the handling of CSV and TXT file loading.

**Comment by junhaow1** [comment]
![Image](https://github.com/user-attachments/assets/6ca7291d-6100-4176-a435-6da32f648844)
