### ISSUE TITLE
TEXT PAGE: Add a popup viewer like image_page (perhaps display the PDF)

### ISSUE THREAD

**Issue by gjwgit** [gjwgit/rattle#538]
It is often convenient to keep the data summary, for example visible while working in other parts of the app. This pop out, just like the image page popup, allows the use to have a separate window containing the text data that may be useful as they work through the app.

One possible implementation is to generate the PDF file in tempDir and then run the operating systme command to open the file, like image_page, using `open` on Mac/Linux and `start` on Windows.

**Comment by junhaow1** [comment]
https://github.com/gjwgit/rattleng/pull/542 PR created

**Comment by junhaow1** [comment]
<img width="1606" alt="image" src="https://github.com/user-attachments/assets/6e521d94-93b9-4bbb-bc74-20d8a6d3a797">
