### ISSUE TITLE
PDF TEXT PAGE: Only the first page is generated - need to handle multiple page documents

### ISSUE THREAD

**Issue by gjwgit** [gjwgit/rattle#546]
The PDF generation looks great.

Some text pages (like Cross Tabulation for the DEMO dataset) are longer than a single page.

We need to be able to output all pages, as required.

**Comment by junhaow1** [comment]
![Image](https://github.com/user-attachments/assets/6306921b-f123-4827-9ecd-7c8cdc51fedf)

**Comment by junhaow1** [comment]
https://github.com/gjwgit/rattleng/pull/549 PR created

**Comment by junhaow1** [comment]
Please review https://github.com/gjwgit/rattleng/pull/510 first , as I merged that branch into this PR
