### ISSUE TITLE
APP: Check if R can be found and if not popup a window warning

### ISSUE THREAD

**Issue by gjwgit** [gjwgit/rattle#556]
## Description

Some users are not following instructions to have R installed and set up on PATH. On starting up Rattle check if R can be started and if not popup an error and do not continue.

**Comment by Lutra-Fs** [comment]
We could enhance this further by implementing a user-configurable R path setting in the application preferences. This would give users more flexibility in their R installation setup.

**Comment by gjwgit** [comment]
Duplicated issue #270
