### ISSUE TITLE
DATASET: Add radio buttons to dataset popup to select Demo dataset

### ISSUE THREAD

**Issue by gjwgit** [gjwgit/rattle#565]
For this DATASET popup add three radio buttons to choose the demo dataset: weather, audit, movies. Then load either weather.csv, audit.csv or movies.csv.

![Image](https://github.com/user-attachments/assets/d40925e9-4f87-46aa-be5a-7105c175df39)

**Comment by junhaow1** [comment]
<img width="438" alt="image" src="https://github.com/user-attachments/assets/4d33e9bf-6996-4326-a2e1-e118c91e85be">

**Comment by gjwgit** [comment]
Can the radio buttons be in a Row please.

**Comment by junhaow1** [comment]
https://github.com/gjwgit/rattleng/pull/568 PR created

**Comment by junhaow1** [comment]
<img width="507" alt="image" src="https://github.com/user-attachments/assets/cb44814a-2588-4fc1-be36-a78c24007f4e">
