### ISSUE TITLE
ROLE: Use Ctrl Tap to extend the selection as a user would expect

### ISSUE THREAD

**Issue by gjwgit** [gjwgit/rattle#581]

**Comment by junhaow1** [comment]
Would the DataTable widget be better for supporting selecting rows in a standard way? fixing here

**Comment by junhaow1** [comment]
![image](https://github.com/user-attachments/assets/85ef179e-3fc5-4284-87bd-a010cbae2ed5)

**Comment by junhaow1** [comment]
demo video: 
https://github.com/user-attachments/assets/1890e8cd-1c7c-4061-a356-9a21125a8963

**Comment by junhaow1** [comment]
branch : https://github.com/gjwgit/rattleng/tree/kev/581_ctrl

**Comment by gjwgit** [comment]
Looking good. Thanks,

**Comment by junhaow1** [comment]
tooltip : 
![image](https://github.com/user-attachments/assets/729dfed1-03a6-4653-af3b-1fe6ad4167a5)

**Comment by junhaow1** [comment]
https://github.com/gjwgit/rattleng/pull/584 PR created
