### ISSUE TITLE
EVALUATE: Add Execute button to build Various Types.

### ISSUE THREAD

**Issue by zheyxu** [gjwgit/rattle#585]

**Comment by zheyxu** [comment]
![Image](https://github.com/user-attachments/assets/0a7c4f82-1b58-4c16-8d69-80cb4b0bb656)
![Image](https://github.com/user-attachments/assets/de7f7b77-2a30-46b8-af85-18d964f2811e)
Made Error Matrix and hand.

**Comment by gjwgit** [comment]
This looks great so far. Worthwhile to now break this down into many smaller tasks to complete and PR.

E.g.,

- [ ] Error Matrix for each model
- [ ] ROC
- [ ] RiskChart for each model
- [ ] Cost Curve
- [ ] Hand
- [ ] Lift
- [ ] Precision
- [ ] Sensistivity

**Comment by gjwgit** [comment]
The Hand plot is generated with something like the following from the bottom of https://bitbucket.org/kayontoga/rattle/src/master/R/evaluate.R

    hmeasure::HMeasure(obs, pr)
    hmeasure::plotROC(result, which=1)
    hmeasure::plotROC(result, which=2)
    hmeasure::plotROC(result, which=3)
    hmeasure::plotROC(result, which=4)"

**Comment by gjwgit** [comment]
Put this on hold for now as we implement the riskchart for tr and tu as part of the model build.

**Comment by gjwgit** [comment]
We can resume focus now on the EVALUATE tab.

**Comment by gjwgit** [comment]
This is the target for implementation as soon as possible now, ideally this week.

Focus on Error Matrix and ROC.

![Image](https://github.com/user-attachments/assets/0453d2a6-8c63-4c0b-90a3-88ff859fd567)

![Image](https://github.com/user-attachments/assets/301b7ffd-ba9e-403c-b755-25a50e9d2298)

**Comment by gjwgit** [comment]
Let's get this as a PR now - essentially a button to BULD the evaluations - demonstrated with error matrix for tree/forest/boost/svm.
