### ISSUE TITLE
VISUAL: Allow 'None' as an option for Group By

### ISSUE THREAD

**Issue by gjwgit** [gjwgit/rattle#589]
As proposed by Bob Muenchen

## Description

In the Group By drop down add an option for None.

When None is chosen then the R code must not do the grouping.

**Comment by junhaow1** [comment]
![image](https://github.com/user-attachments/assets/f9f39f0b-3340-410c-879b-f5e4be920045)
![image](https://github.com/user-attachments/assets/fae7febf-e5c1-469c-9e49-7f9d23115613)

**Comment by junhaow1** [comment]
https://github.com/gjwgit/rattleng/pull/593 PR created

**Comment by junhaow1** [comment]
This is more than just adding 'None' to the drop down - otherwise what is the point.

The appropriate R code templates need to be updated to handle no grouping of the variable. This might need r/source.dart updates to communicate to the scripts that there is no group by required. GROUP_BY.

**Comment by junhaow1** [comment]
https://github.com/gjwgit/rattleng/pull/613 PR created

**Comment by junhaow1** [comment]
Another issue created https://github.com/gjwgit/rattleng/issues/614
