### ISSUE TITLE
SETTINGS: Add a setting for the app to use when popout an image

### ISSUE THREAD

**Issue by gjwgit** [gjwgit/rattle#590]
Proposed by Bob Muenchen

## Description

Add a setting to control the external program that is run when opening the image in a popout. The current default is `open`  on Linux and macOS and `start` on Windows. A user may like to override it to be `inkscape` instead. So in image_page.dart check for the `settingsImageViewerProvider`  which is defaulted to open or start depending on OS, and in SETTINGS might be overridden to be, for example, `inkscape`.

**Comment by gjwgit** [comment]
- [x] The SETTINGS page should have image viewer as a text field where the default value is open on Linux/MacOS and start on Windows. I can then type 'inkscape' myself, or any other program to run that I choose.
- [x] The SETTINGS should be alphabetic in order, so IMAGE VIEWER comes after GRAPHICS and before SESSION.

**Comment by gjwgit** [comment]
Ready to test on Linux - @gjwgit

**Comment by junhaow1** [comment]
https://github.com/gjwgit/rattleng/tree/kev/590_popup working branch 
ready to test for linux @gjwgit

**Comment by gjwgit** [comment]
This works for me on Linux with inkscape set to on. I would like to choose different apps though - so the need for a textfield rather than a toggle. For example I might want to change inkscpre  to gimp or eog or any other app I might have available to display an image.

**Comment by junhaow1** [comment]
![Image](https://github.com/user-attachments/assets/b9eba746-4f2b-4e6d-9ee5-34c16268e56e)
Hi @gjwgit  could you please pull the latest changes? I've added a textfield 2 hours ago. :)

**Comment by gjwgit** [comment]
Thanks. 

- [x] Please limit the textfield width to be 12 characters.
- [x] Be sure to merge the latest dev - I have updated the layout of settings with a Divider between sections.

On first try I got this:

```
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Null check operator used on a null value
#0      ImagePage.build.<anonymous closure>.<anonymous closure> (package:rattle/widgets/image_page.dart:271:61)
<asynchronous suspension>
```

but it is okay now. Odd

**Comment by junhaow1** [comment]
![Image](https://github.com/user-attachments/assets/d5b56005-4fdb-4cc2-8fd0-51f92b6f0719)

**Comment by junhaow1** [comment]
https://github.com/gjwgit/rattleng/pull/626 PR created
