### ISSUE TITLE
VISUAL: Add a Ignore Missing checkbox and pass through to R scripts

### ISSUE THREAD

**Issue by gjwgit** [gjwgit/rattle#595]
## Description 

Add a check box, default to selected, label is `Ignore Missing Group by`, place it after the Variable and Group by selections.

## Why

So that as as data scientist I can explore the missing groups in the group by, or not, as I decide. IN the plot below, the NA column should not be show if IGNORE MISSING GROUP BY is selected. 

This will need communicating the IGNORE_MISSING_GROUP_BY to R in r/source. It would be TRUE or FALSE.

## Context

![Image](https://github.com/user-attachments/assets/c07bf840-e841-4238-8755-8d49ee727cf3)

**Comment by junhaow1** [comment]
![image](https://github.com/user-attachments/assets/dd3afa78-f89d-4c65-be66-593829009510)

**Comment by junhaow1** [comment]
https://github.com/gjwgit/rattleng/pull/657 PR created
