### ISSUE TITLE
SETTINGS: Theme Not Applied on Startup Until SettingsDialog is Opened

### ISSUE THREAD

**Issue by junhaow1** [gjwgit/rattle#598]
## Description
When starting up the app, the selected theme is not applied to generating plots unless the SettingsDialog is opened first. This issue seems to arise because the theme changes are not being applied during the app initialization or when navigating to the HomeScreen or ExploreTabs. The system may require explicitly applying the saved theme during these transitions.

## Why
This issue negatively impacts the user experience, as the theme is expected to be consistent across all app functionalities upon startup. Users should not have to interact with the SettingsDialog to apply their saved preferences. Fixing this ensures the app respects user settings immediately, providing a seamless and intuitive experience.

## Closing Criteria

- [x]  Ensure the theme is applied during app startup without requiring interaction with the SettingsDialog.

- [x]  Verify the theme is correctly applied when navigating to the HomeScreen or ExploreTabs.
- [x]  Confirm that theme preferences persist across app restarts without additional user intervention.

**Comment by gjwgit** [comment]
I have removed the theme setting to the default on startup. I think that works now - in #324.

I have added the SETTINGS_GRAPHIC_THEME to the R scripts that use the theme so we don't need to execute the `theme_default <- SETTINGS_GRAPHIC_THEME` there.

Let's see if that can simplify things.

I have added `Theme` to the Debug tab so we ca see what's happening.

Seems to be working. Can you please check. Thanks

**Comment by junhaow1** [comment]
> I have removed the theme setting to the default on startup. I think that works now - in #324.
> 
> I have added the SETTINGS_GRAPHIC_THEME to the R scripts that use the theme so we don't need to execute the `theme_default <- SETTINGS_GRAPHIC_THEME` there.
> 
> Let's see if that can simplify things.
> 
> I have added `Theme` to the Debug tab so we ca see what's happening.
> 
> Seems to be working. Can you please check. Thanks

I have tested. It is working now. Thanks heaps. We could close this issue.
