### ISSUE TITLE
SETTINGS: Add checkbox `Ask before quit`

### ISSUE THREAD

**Issue by gjwgit** [gjwgit/rattle#599]
## Description

Currently on exit the user is asked to confirm quit with the popup we can see below. This setting will toggle whether that happens or not.  The default is ON. When ON the popup will appear. When OFF the application will just exit without the POPUP when the user quits.

Add this to a section in SETTINGS called 'Session Control'

## Why

So that as an advanced user I am not annoyed having to click OKAY to quit every time.

![Image](https://github.com/user-attachments/assets/3e185678-9250-4407-ac50-eb305de06afa)

**Comment by junhaow1** [comment]
https://github.com/gjwgit/rattleng/tree/kev/599_quit working branch. PR will be ready soon

**Comment by junhaow1** [comment]
![image](https://github.com/user-attachments/assets/a2486584-9a1e-4190-b4bd-96fc0debc152)

**Comment by junhaow1** [comment]
https://github.com/gjwgit/rattleng/pull/610 PR created
