### ISSUE TITLE
VISUAL: Add radio button for BOXPLOT_NOTCH

### ISSUE THREAD

**Issue by gjwgit** [gjwgit/rattle#601]
## Description

Add a check button to the EXPLORE -> VISUAL -> BOXPLOT config ( on the first row after the IGNORE MISSING GROUP BY rather than on the second row as in the picture below) labelled as `Box Plot Notch` with a tooltip and enabled  by default.

Create a provider for it in `providers/visualise.dart` as `exploreVisualBoxplotNotchProvider`.

Use the provider in `r/source.dart` for BOXPLOT_NOTCH - currently it is fixed as FALSE.

When not enabled the following will be shown:

![Image](https://github.com/user-attachments/assets/aec3e8bc-2702-48e9-8859-958c70c47c33)

**Comment by junhaow1** [comment]
https://github.com/gjwgit/rattleng/pull/667 PR created
