### ISSUE TITLE
RESET: On a reset/loading new dataset, reset all tabs to the first feature

### ISSUE THREAD

**Issue by gjwgit** [gjwgit/rattle#604]
## Description

On loading a dataset or resetting the dataset, currently if, for example, EXPLORE was previously on SUMMARY, the after loading the dataset EXPLORE is still on the SUMMARY feature. It should be back on the OVERVIEW feature after loading a new dataset. Same for all tabs.

Particular use case:

1. DEMO weather
2. EXPLORE SUMMARY BUILD
3. RESET
4. DEMO sherlock
5. EXPLORE - SUMMARY is selected but the whole of the EXPLORE tab is currently ignored (as it should be for the text dataset sherlock. Instead the OVERVIEW should be displayed.

**Comment by junhaow1** [comment]
1. DEMO weather
2. EXPLORE SUMMARY BUILD
3. RESET
4. DEMO sherlock
5. EXPLORE - **OVERVIEW** is selected 

![image](https://github.com/user-attachments/assets/8e55b4db-becc-496b-9639-e4b99e358819)


https://github.com/gjwgit/rattleng/pull/663 PR created

**Comment by gjwgit** [comment]
This is fixed as advertised. Thanks.
