### ISSUE TITLE
VISUAL: Fix "None" Option for Group By Reverting to rain_tomorrow on Linux

### ISSUE THREAD

**Issue by junhaow1** [gjwgit/rattle#614]
## Description
In the Visual page, selecting "None" for the Group By option and tapping the BUILD button results in "None" being replaced with the value rain_tomorrow in the GUI. While the generated plots are correct and respect the "None" setting, the GUI rebuild incorrectly changes the displayed Group By value back to rain_tomorrow. This issue occurs only on Linux and not on Windows.

## Why
This bug creates an inconsistent user experience on Linux, leading to confusion about whether the Group By setting has been correctly applied. Although the plots are accurate, the GUI should reflect the selected "None" value, ensuring clarity and trust in the system's behavior. Addressing this issue will enhance the usability and reliability of the application across platforms.

## Closing Criteria

- [ ]  When "None" is selected for Group By, it remains displayed as "None" in the GUI after tapping BUILD.

- [ ]  The issue is confirmed to be resolved on Linux platforms.
- [ ]  The behavior remains consistent and unaffected on Windows.

**Comment by junhaow1** [comment]
![image](https://github.com/user-attachments/assets/066412d1-e07d-410b-b046-34215a93d1b8)

**Comment by gjwgit** [comment]
https://github.com/user-attachments/assets/a6503566-bcdd-4c5a-bce4-06e73b59441d

**Comment by gjwgit** [comment]
Found bug and fixed. Odd that it did not have the same issue on Windows???
