### ISSUE TITLE
CLUSTER: Replace CLUSTER_SEED with RANDOM_SEED

### ISSUE THREAD

**Issue by gjwgit** [gjwgit/rattle#622]
## Description

Currently CLUSTER_SEED is obtained from seedClusterProvider.

Rename CLUSTER_SEED to RANDOM_SEED and so used RANDOM_SEED throughout the app - dart and R code.

**Comment by junhaow1** [comment]
https://github.com/gjwgit/rattleng/pull/624 PR created
