### ISSUE TITLE
SETTINGS: DataSet Toggles toggle widgets and their text each need a MarkdownTooltip

### ISSUE THREAD

**Issue by gjwgit** [gjwgit/rattle#627]

**Comment by junhaow1** [comment]
![image](https://github.com/user-attachments/assets/25f6a6d0-ff82-4cfe-a0e4-00095a172f2d)
![image](https://github.com/user-attachments/assets/245c1f87-dcb1-401e-8785-81af12ffe648)

![image](https://github.com/user-attachments/assets/8c1ed763-ed30-498f-b27b-efaae65689da)
![image](https://github.com/user-attachments/assets/83023f5f-39e3-41c9-ba70-976d0348cb96)

![image](https://github.com/user-attachments/assets/4865e047-921d-46f0-8028-6a0c39f9f302)
![image](https://github.com/user-attachments/assets/a859590d-63da-4c3f-b3f2-5f748cc67a65)

![image](https://github.com/user-attachments/assets/fff1be44-76d6-444c-9d28-0474684ff893)
![image](https://github.com/user-attachments/assets/98734578-a44a-4ede-ab12-0cfdd35c5f9a)

**Comment by junhaow1** [comment]
![image](https://github.com/user-attachments/assets/eb6c1d63-f6cc-40c6-b3f2-df8d2b5e3897)
![image](https://github.com/user-attachments/assets/0ff2faa5-e802-4539-b30b-73d48b2bed2a)

![image](https://github.com/user-attachments/assets/b87ffd45-f14a-4f3a-a46f-aafc5e2a5dac)
![image](https://github.com/user-attachments/assets/22186679-e92d-4855-bba8-b9ab3fc58f8c)


![image](https://github.com/user-attachments/assets/f029b199-3412-4afa-bf40-f98773f7f0c4)
![image](https://github.com/user-attachments/assets/4810dfa9-bb61-4975-967b-872f7998507a)


![image](https://github.com/user-attachments/assets/2a320638-2b02-401e-80f9-94bf31dc8049)

![image](https://github.com/user-attachments/assets/389e4a78-71f3-4889-a18d-9f4e90024c4d)

**Comment by junhaow1** [comment]
https://github.com/gjwgit/rattleng/pull/648 PR created
