### ISSUE TITLE
RANDOMISE: Add a new button top right to randomly change the seed and save it

### ISSUE THREAD

**Issue by gjwgit** [gjwgit/rattle#651]
## Description

- [x] Add a new button between RESET and R PACKAGES to change the random seed easily (without opening SETTINGS).
- [x] The new random number should be saved between session
- [x] Perhaps use Icon.shuffle for the button.
- [x] The button should not be enabled until a dataset is loaded.
- [x] The button should not be enabled if the PARTITION toggle is off.

## Why

As a data scientist I want to be able to randomly change the partitioning of the dataset for example and see the impact on the resulting model. This will allow for a quick resampling of the data for testing the models.

**Comment by junhaow1** [comment]
https://github.com/user-attachments/assets/92cd596b-9c9b-49cd-b678-8e6309e5695d

**Comment by junhaow1** [comment]
https://github.com/gjwgit/rattleng/pull/658 PR created
