### ISSUE TITLE
SETTINGS: Tuning -> Validation

### ISSUE THREAD

**Issue by gjwgit** [gjwgit/rattle#656]
## Description

- [x] Add a SETTING toggle with the label `Use Validation rather than Tuning for Evaluation`
- [x] It is FALSE by default
- [x] Its value is aved between session under user-preferences
- [x] When TRUE change wording in the GUI from Tuning to Validation

## Why

The common phrasing is train/validate/test. I have **always** preferred train/tune/test as more descriptive. We use this dataset to tune the mode rather than to validate the model which is really the task of the final test dataset. 

Internally I will use tr/tu/te but externally we can use either Tuning or Validation.

**Comment by gjwgit** [comment]
Claude says:

```
Both approaches are valid but serve slightly different purposes. Let me explain the key differences:
Train/Validate/Test split:

Training set: Used to train the model
Validation set: Used during training to evaluate model performance and prevent overfitting
Test set: Held out completely until final evaluation

Train/Tune/Test split:

Training set: Used for initial model training
Tuning set: Used for hyperparameter optimization
Test set: Held out completely until final evaluation

The main difference is in how the middle set is used:

Validation focuses on monitoring training progress and early stopping
Tuning focuses on finding optimal hyperparameters

In practice, many people use "validation" and "tuning" sets interchangeably. 
However, for the most rigorous approach, you might want to consider:

Train/Validate/Tune/Test - where you have:


Training data for model training
Validation data for early stopping
Tuning data for hyperparameter optimization
Test data for final evaluation

```

**Comment by yixiangyin** [comment]
<img width="1362" alt="Screenshot 2024-12-19 at 14 40 02" src="https://github.com/user-attachments/assets/ad1774c2-25a2-4c91-8b45-9074a4dacb09" />
