### ISSUE TITLE
RANDOM SEED: After changing the seed if PARTITION then re-partition the dataset

### ISSUE THREAD

**Issue by gjwgit** [gjwgit/rattle#660]

**Comment by junhaow1** [comment]
![Image](https://github.com/user-attachments/assets/7cf47407-f567-4b72-8d14-98952c62c42b)
![Image](https://github.com/user-attachments/assets/afe04429-444d-48f1-813b-694987ffcbeb)

**After changing the seed number :** 


![Image](https://github.com/user-attachments/assets/c55666c5-043e-4639-85bc-9c3726f0a2d4)
![Image](https://github.com/user-attachments/assets/cc5acb0d-0e78-4837-b625-191eb0ca1038)

**Comment by junhaow1** [comment]
> ![Image](https://github.com/user-attachments/assets/7cf47407-f567-4b72-8d14-98952c62c42b) ![Image](https://github.com/user-attachments/assets/afe04429-444d-48f1-813b-694987ffcbeb)
> 
> **After changing the seed number :**
> 
> ![Image](https://github.com/user-attachments/assets/c55666c5-043e-4639-85bc-9c3726f0a2d4) ![Image](https://github.com/user-attachments/assets/cc5acb0d-0e78-4837-b625-191eb0ca1038)

working branch https://github.com/gjwgit/rattleng/tree/kev/660_change_seed_re_partition. Hi @gjwgit , looks like it is working now.

**Comment by junhaow1** [comment]
![image](https://github.com/user-attachments/assets/6b41af30-7504-4c6a-8fde-a6dce13c7a90)
![image](https://github.com/user-attachments/assets/700ddf74-7976-45c2-8c87-7e0bf7f31398)

Already merged into Dev

**Comment by junhaow1** [comment]
Could you please test this and close this ticket? @gjwgit
