### ISSUE TITLE
SETTINGS: Add option to partition the dataset differently

### ISSUE THREAD

**Issue by gjwgit** [gjwgit/rattle#662]
## Description

Currently the default partitioning of the dataset is 70/15/15 as set through DATA_SPLIT_TR_TU_TE in r/source.dart.

This task will add a new provider `partitionSettingProvider` with the default being `0.7, 0.15, 0.15`.

An option in SETTINGS will allow the user to change this. It will be displayed as 70/15/15 to the user. The user might change it to `50/25/25` for example. This is communicated to the R scripts as `0.5, 0.25, 0.25`.

## Why

So that as a data scientist I can experiment with different sized datasets to explore how that affects the model.

**Comment by junhaow1** [comment]
![Image](https://github.com/user-attachments/assets/47d0bfef-8fa7-40d2-a59f-4b30d056046d)

**Comment by gjwgit** [comment]
Suggest reduce width of the numeric boxes, and to use something like:

![Image](https://github.com/user-attachments/assets/6aca2011-96b1-42ce-8bb9-515d0f0bbd09)

Perhaps also add a fourth box with is the sum of the other boxes (should be 100).

**Comment by junhaow1** [comment]
![Image](https://github.com/user-attachments/assets/fe8fcda0-54d6-4db4-a9c2-70bba01644af)

**Comment by gjwgit** [comment]
Looks great. Can we have a Text label to the right of the three fields that is updated dynamically to be the sum of the three fields? If easy enough, then do now, it more difficult then please create a separate issue.

**Comment by junhaow1** [comment]
https://github.com/gjwgit/rattleng/pull/686 PR created

**Comment by junhaow1** [comment]
> Looks great. Can we have a Text label to the right of the three fields that is updated dynamically to be the sum of the three fields? If easy enough, then do now, it more difficult then please create a separate issue.

Will create another ticket to rename Validation to Tuning . and have a text label to the right of three fields

**Comment by junhaow1** [comment]
- [x] On changing the values in SETTINGS, close SETTINGS, open SETTINGS, they are back to the original defaults?
- [x] The changes are not seen in the R code? 
- [x] Typing in actual values is very odd - e.g., try entering 60 over 70 it is difficult?
- [x] Each field should only allow 0-100.
- [x] The total should be 100

**Comment by gjwgit** [comment]
For now replace the number fields with simple text/numeric fields and push the blocker of the number fields not working to other issue(s) and get this working simply and into a PR asap.

**Comment by junhaow1** [comment]
![image](https://github.com/user-attachments/assets/0bd76c14-6a56-437f-a84c-63e9702c6d15)
![image](https://github.com/user-attachments/assets/cb8f37f4-c7e7-49de-9fbc-8fb035b9b8f3)

![image](https://github.com/user-attachments/assets/f9d74c2a-0501-4e26-933a-2d5fd6ab771e)
