### ISSUE TITLE
EVALUATE: Implement ROC/AUC plots for all models

### ISSUE THREAD

**Issue by gjwgit** [gjwgit/rattle#664]
Display this ROC/AUC curve after the Error Matrix page.

![Image](https://github.com/user-attachments/assets/e31bcc88-7ec2-450e-b53c-816b2fc19e49)

**Comment by zheyxu** [comment]
<img width="1461" alt="Image" src="https://github.com/user-attachments/assets/091f31f2-b4f0-4eb6-8037-d651f9736529" />

**Comment by gjwgit** [comment]
Title needs some work but otherwise looks great. Thanks.

**Comment by zheyxu** [comment]
Updated:
<img width="1004" alt="Image" src="https://github.com/user-attachments/assets/00049296-9ff7-4d0f-ac90-7713b023c7ee" />

**Comment by zheyxu** [comment]
<img width="815" alt="Image" src="https://github.com/user-attachments/assets/e659586f-ed0c-4586-bd99-9c273f59ca2e" />
After removing some NAs, some model has ROC = 1. Need discussion.

**Comment by zheyxu** [comment]
Made pr https://github.com/gjwgit/rattleng/pull/712
