### ISSUE TITLE
NAVIGATE: On a dataet RESET ensure MODEL tab reverts to the overview page

### ISSUE THREAD

**Issue by gjwgit** [gjwgit/rattle#669]
Like you did for EXPLORE, after a new dataset is loaded (RESET) the MODEL tab needs to reset to the first feature, OVERVIEW.

Load WEATHER -> MODEL -> ASSOCIATIONS -> DATASET -> MOVIE -> -> MODEL

The resulting feature is ASSOCIATIONS

![Image](https://github.com/user-attachments/assets/6fab37c9-e659-4693-aa4f-e4ce0551ebc1)

**Comment by junhaow1** [comment]
MODEL/TRANSFORM are also implemented. We could close this issue I assume

**Comment by junhaow1** [comment]
https://github.com/user-attachments/assets/a5ca5db9-3d48-4d29-981a-06f8b6e28bd4

**Comment by junhaow1** [comment]
https://github.com/gjwgit/rattleng/pull/670 PR created

**Comment by junhaow1** [comment]
The reason this was not working is that, in the last ticket, I added the implementation for the reset icon in the top-right corner. In this issue, I also added the implementation for the dataset button in the dataset tab.
