### ISSUE TITLE
DATASET POPUP: Replace the radio buttons with actual buttons - each chooses the dataset

### ISSUE THREAD

**Issue by gjwgit** [gjwgit/rattle#671]
## Description

Where we currently Have a DEMO button, remove that and replace each of the 4 radio buttons into actual buttons that load the corresponding demo dataset.

![Image](https://github.com/user-attachments/assets/86503cf6-4939-471d-b130-28485748da6f)

# Why

So that the user can load a demo dataset with 1 less click

**Comment by junhaow1** [comment]
![image](https://github.com/user-attachments/assets/67705ac0-0bcf-4776-bf51-910459f84bef)

**Comment by junhaow1** [comment]
https://github.com/gjwgit/rattleng/pull/688 PR created
