### ISSUE TITLE
DATASET: On loading PROTEIN dataset the Country can not be changed from IGNORE

### ISSUE THREAD

**Issue by gjwgit** [gjwgit/rattle#675]
The variable country is set as IGNORE by default. Can't change it to anything else except TARGET.

- [x] It should not be IGNORE by default.
- [x] It should not override user choices
- [x] For a dataset of all numerics and on categoric, set the categoric to TARGET or IDENT by default. If all rows have a unique value then it is IDENT. If not then TARGET

**Comment by junhaow1** [comment]
dataset display logic

**Comment by gjwgit** [comment]
The code is in **two** places (bad practice). I have removed the IGNORE heuristic for now. 

We probably need to consider moving the heuristic code to the dataset load, set the metaData, and then populate the roles form the metaData.
