### ISSUE TITLE
EVALUATE: Review pred_ra and prob_ra for Neural

### ISSUE THREAD

**Issue by gjwgit** [gjwgit/rattle#677]
The building of a predictive model for classification with nnet and neural is failing, predicting all in one class or else NA. 

V5 only implements nnet but also predicts all 0:

```
Error matrix for the Neural Net model on audit.csv [validate] (counts):

      Predicted
Actual   0 Error
     0 226     0
     1  64   100

Error matrix for the Neural Net model on audit.csv [validate] (proportions):

      Predicted
Actual    0 Error
     0 77.9     0
     1 22.1   100

Overall error: -77.9%, Averaged class error: 50%
```

**Comment by zheyxu** [comment]
Neural net model seems that in different format of trds[[target]] (a list of 'Yes' and 'No')

<img width="911" alt="Image" src="https://github.com/user-attachments/assets/3e02520c-82f2-4c02-b239-435e23c80798" />

**Comment by zheyxu** [comment]
Made pr https://github.com/gjwgit/rattleng/pull/681 for nnet.

**Comment by gjwgit** [comment]
@gjwgit to have a look at the neuralnet predict() issue.,

**Comment by gjwgit** [comment]
![Image](https://github.com/user-attachments/assets/59229ed0-cce6-4ad1-bbf7-7232feb605de)

Need to confirm how neuralnet predicts and to ensure the results are correct.

**Comment by gjwgit** [comment]
- [x] Create TESTING audit_evaluate_nnet.dart: For the audit dataset, ignore all factors, rescale numeric, drop ignored, build nnet  and check the resulting error matrix. Looks okay
- [x] Similarly for neuralnet()

**Comment by gjwgit** [comment]
Move to using tidymodels rather than trying to fix this in general.
