### ISSUE TITLE
EVALUATE: Support choice of TR, TU, TE, FULL datasets

### ISSUE THREAD

**Issue by gjwgit** [gjwgit/rattle#683]
The evaluation needs to be undertaken on any one of the datasets.

![Image](https://github.com/user-attachments/assets/9354d619-b98e-4eab-bd2f-ee767b12883a)

- [x] If Training the use `trds`
- [x] If Tuning then use `tuds`
- [x] If Testing the use `teds`
- [x] If Full then use `tcds` 

- [ ] Check the `validationForTuningSettingProvider` and if true use `Validation` and if false use `Tuning` for the chip and tooltip.

**Comment by zheyxu** [comment]
For the point, there is already a variable **useValidationSettingProvider** to define.

- [ ] Check the validationForTuningSettingProvider and if true use Validation and if false use Tuning for the chip and tooltip.

https://github.com/gjwgit/rattleng/blob/f2e964d3f9c76431ad9a0703861aa10217c95bef/lib/features/dataset/toggles.dart#L133

**Comment by zheyxu** [comment]
Made pr https://github.com/gjwgit/rattleng/pull/723
