### ISSUE TITLE
TREE: Console error for WIndows

### ISSUE THREAD

**Issue by junhaow1** [gjwgit/rattle#687]

**Comment by junhaow1** [comment]
![Image](https://github.com/user-attachments/assets/a5d63eb9-3ded-41d4-9767-de887f71aa4d)


![Image](https://github.com/user-attachments/assets/beca9ebf-264c-4a8a-8087-6aa7fa7d8050)


![Image](https://github.com/user-attachments/assets/ec59bc2f-c705-4d6b-ae44-6026abfe15d7)

**Comment by junhaow1** [comment]
First error: > meta_data(ds)
Error in list(datatype = "other", unique = length(unique(x)), missing = sum(is.na(x)),  :
  argument 4 is empty

**Comment by gjwgit** [comment]
Issue was missing package.
