### ISSUE TITLE
SETTINGS: Add a toggle to always randomise paritioning for RANDOM_PARTITION template variable

### ISSUE THREAD

**Issue by gjwgit** [gjwgit/rattle#689]
## Description

Under the SETTINGS -> RANDOM SEED section add a toggle labelled `Random Partition each Model Build` and have it set to off by default.

This will be used for the template variable RANDOM_PARTITION in r/source.dart. It is currently always set to FALSE. This toggle will set it to TRUE or FALSE.

It is already implemented in the R code model_template.R

**Comment by junhaow1** [comment]
![image](https://github.com/user-attachments/assets/688ee3f8-8664-4f71-afd3-d47b2753015b)

**Comment by junhaow1** [comment]
https://github.com/gjwgit/rattleng/pull/700 PR created
