### ISSUE TITLE
SCRIPT: Move the SAVE button to the top right with icon just like text_page

### ISSUE THREAD

**Issue by gjwgit** [gjwgit/rattle#696]
## Description

Remove the SAVE button we see here nd replace it with the SAVE icon in the top right like we see in the second screenshot.

![Image](https://github.com/user-attachments/assets/23320101-15b7-4982-945e-3b7947e9df11)

![Image](https://github.com/user-attachments/assets/6e804707-f2b4-4d67-a59b-edeb411e472e)

## Why

So that the SAVE operation is always up in the right as this is where we are training the user to find the SAVE button.

**Comment by junhaow1** [comment]
![image](https://github.com/user-attachments/assets/d8ee6fc4-2c96-4dde-879c-97b23647e9bf)

**Comment by junhaow1** [comment]
https://github.com/gjwgit/rattleng/pull/701 PR created
