### ISSUE TITLE
SCRIPTS: Move the scroll bar to the far right

### ISSUE THREAD

**Issue by gjwgit** [gjwgit/rattle#703]
## Description

The scroll bar is currently just to the right of the text. Please move it to the far right. This used to be the behaviour prior to moving the SAVE icon.

## Why

As a user I expect to find the scroll bar to the far right. This is how it is in most other pages now.

## Detail

Previously:

![Image](https://github.com/user-attachments/assets/e6bae076-b9a7-4f85-8330-9b68ddf2528c)

kev/696_script_save_button_top_right

![Image](https://github.com/user-attachments/assets/459f9f8c-1be5-4621-971d-f4c9358d7b91)

**Comment by junhaow1** [comment]
![image](https://github.com/user-attachments/assets/2c4ad1ea-9345-41a5-881d-94bfb7551a57)

**Comment by junhaow1** [comment]
https://github.com/gjwgit/rattleng/pull/707 PR created
