### ISSUE TITLE
SCRIPT: Left overview should be top aligned

### ISSUE THREAD

**Issue by gjwgit** [gjwgit/rattle#704]
## Description

The overview section `The R Script`  should be top aligned.

## Why

So that it is like all over overview sections.

##Detail

![Image](https://github.com/user-attachments/assets/8f58f6be-64c0-4bb2-8a2e-c452bef2666f)

**Comment by junhaow1** [comment]
![image](https://github.com/user-attachments/assets/29249e4d-6228-4b40-80d5-dff113bdf7ee)

**Comment by junhaow1** [comment]
https://github.com/gjwgit/rattleng/pull/706 PR created
