### ISSUE TITLE
SCRIPT: Add a graphic below to fill the space

### ISSUE THREAD

**Issue by gjwgit** [gjwgit/rattle#705]
## Description

Add a small graphic to convey the idea of running an R script. This should be in the space below the text in the left column.

## Why

To add some engagement to the page.

## Detail

![Image](https://github.com/user-attachments/assets/8f58f6be-64c0-4bb2-8a2e-c452bef2666f)

**Comment by junhaow1** [comment]
https://github.com/gjwgit/rattleng/pull/706 PR created

**Comment by junhaow1** [comment]
![image](https://github.com/user-attachments/assets/1418051f-27b0-4fac-92aa-f5523888c4d8)

**Comment by junhaow1** [comment]
https://github.com/gjwgit/rattleng/pull/708 PR created

**Comment by gjwgit** [comment]
SVG Issue noted in the PR.
